// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie/movie_req_res.proto

package com.movieplatform.proto.movie;

public interface CrewMemberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.movie.CrewMember)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string person_id = 1;</code>
   * @return The personId.
   */
  java.lang.String getPersonId();
  /**
   * <code>string person_id = 1;</code>
   * @return The bytes for personId.
   */
  com.google.protobuf.ByteString
      getPersonIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Director/Producer/etc.
   * </pre>
   *
   * <code>string job = 3;</code>
   * @return The job.
   */
  java.lang.String getJob();
  /**
   * <pre>
   * Director/Producer/etc.
   * </pre>
   *
   * <code>string job = 3;</code>
   * @return The bytes for job.
   */
  com.google.protobuf.ByteString
      getJobBytes();

  /**
   * <pre>
   * Department
   * </pre>
   *
   * <code>string department = 4;</code>
   * @return The department.
   */
  java.lang.String getDepartment();
  /**
   * <pre>
   * Department
   * </pre>
   *
   * <code>string department = 4;</code>
   * @return The bytes for department.
   */
  com.google.protobuf.ByteString
      getDepartmentBytes();

  /**
   * <pre>
   * Credit order
   * </pre>
   *
   * <code>int32 order = 5;</code>
   * @return The order.
   */
  int getOrder();
}
