// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie/movie_req_res.proto

package com.movieplatform.proto.movie;

public interface PublishMovieResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.movie.PublishMovieResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  boolean hasBaseResponse();
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  com.movieplatform.proto.common.BaseResponse getBaseResponse();
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder();

  /**
   * <pre>
   * Published movie
   * </pre>
   *
   * <code>.proto.movie.Movie movie = 2;</code>
   * @return Whether the movie field is set.
   */
  boolean hasMovie();
  /**
   * <pre>
   * Published movie
   * </pre>
   *
   * <code>.proto.movie.Movie movie = 2;</code>
   * @return The movie.
   */
  com.movieplatform.proto.movie.Movie getMovie();
  /**
   * <pre>
   * Published movie
   * </pre>
   *
   * <code>.proto.movie.Movie movie = 2;</code>
   */
  com.movieplatform.proto.movie.MovieOrBuilder getMovieOrBuilder();

  /**
   * <pre>
   * Publication timestamp
   * </pre>
   *
   * <code>.proto.common.DateTime published_at = 3;</code>
   * @return Whether the publishedAt field is set.
   */
  boolean hasPublishedAt();
  /**
   * <pre>
   * Publication timestamp
   * </pre>
   *
   * <code>.proto.common.DateTime published_at = 3;</code>
   * @return The publishedAt.
   */
  com.movieplatform.proto.common.DateTime getPublishedAt();
  /**
   * <pre>
   * Publication timestamp
   * </pre>
   *
   * <code>.proto.common.DateTime published_at = 3;</code>
   */
  com.movieplatform.proto.common.DateTimeOrBuilder getPublishedAtOrBuilder();
}
