// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie/movie_req_res.proto

package com.movieplatform.proto.movie;

/**
 * <pre>
 * Validate movie request
 * </pre>
 *
 * Protobuf type {@code proto.movie.ValidateMovieRequest}
 */
public final class ValidateMovieRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.movie.ValidateMovieRequest)
    ValidateMovieRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ValidateMovieRequest.newBuilder() to construct.
  private ValidateMovieRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ValidateMovieRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ValidateMovieRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_ValidateMovieRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_ValidateMovieRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.movie.ValidateMovieRequest.class, com.movieplatform.proto.movie.ValidateMovieRequest.Builder.class);
  }

  public static final int BASE_REQUEST_FIELD_NUMBER = 1;
  private com.movieplatform.proto.common.BaseRequest baseRequest_;
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return Whether the baseRequest field is set.
   */
  @java.lang.Override
  public boolean hasBaseRequest() {
    return baseRequest_ != null;
  }
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return The baseRequest.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseRequest getBaseRequest() {
    return baseRequest_ == null ? com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
  }
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseRequestOrBuilder getBaseRequestOrBuilder() {
    return baseRequest_ == null ? com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
  }

  public static final int MOVIE_FIELD_NUMBER = 2;
  private com.movieplatform.proto.movie.Movie movie_;
  /**
   * <pre>
   * Movie to validate
   * </pre>
   *
   * <code>.proto.movie.Movie movie = 2;</code>
   * @return Whether the movie field is set.
   */
  @java.lang.Override
  public boolean hasMovie() {
    return movie_ != null;
  }
  /**
   * <pre>
   * Movie to validate
   * </pre>
   *
   * <code>.proto.movie.Movie movie = 2;</code>
   * @return The movie.
   */
  @java.lang.Override
  public com.movieplatform.proto.movie.Movie getMovie() {
    return movie_ == null ? com.movieplatform.proto.movie.Movie.getDefaultInstance() : movie_;
  }
  /**
   * <pre>
   * Movie to validate
   * </pre>
   *
   * <code>.proto.movie.Movie movie = 2;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.movie.MovieOrBuilder getMovieOrBuilder() {
    return movie_ == null ? com.movieplatform.proto.movie.Movie.getDefaultInstance() : movie_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseRequest_ != null) {
      output.writeMessage(1, getBaseRequest());
    }
    if (movie_ != null) {
      output.writeMessage(2, getMovie());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseRequest());
    }
    if (movie_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMovie());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.movie.ValidateMovieRequest)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.movie.ValidateMovieRequest other = (com.movieplatform.proto.movie.ValidateMovieRequest) obj;

    if (hasBaseRequest() != other.hasBaseRequest()) return false;
    if (hasBaseRequest()) {
      if (!getBaseRequest()
          .equals(other.getBaseRequest())) return false;
    }
    if (hasMovie() != other.hasMovie()) return false;
    if (hasMovie()) {
      if (!getMovie()
          .equals(other.getMovie())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseRequest()) {
      hash = (37 * hash) + BASE_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getBaseRequest().hashCode();
    }
    if (hasMovie()) {
      hash = (37 * hash) + MOVIE_FIELD_NUMBER;
      hash = (53 * hash) + getMovie().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.movie.ValidateMovieRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.movie.ValidateMovieRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.ValidateMovieRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.movie.ValidateMovieRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.ValidateMovieRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.movie.ValidateMovieRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.ValidateMovieRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.movie.ValidateMovieRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.ValidateMovieRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.movie.ValidateMovieRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.ValidateMovieRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.movie.ValidateMovieRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.movie.ValidateMovieRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Validate movie request
   * </pre>
   *
   * Protobuf type {@code proto.movie.ValidateMovieRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.movie.ValidateMovieRequest)
      com.movieplatform.proto.movie.ValidateMovieRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_ValidateMovieRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_ValidateMovieRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.movie.ValidateMovieRequest.class, com.movieplatform.proto.movie.ValidateMovieRequest.Builder.class);
    }

    // Construct using com.movieplatform.proto.movie.ValidateMovieRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseRequest_ = null;
      if (baseRequestBuilder_ != null) {
        baseRequestBuilder_.dispose();
        baseRequestBuilder_ = null;
      }
      movie_ = null;
      if (movieBuilder_ != null) {
        movieBuilder_.dispose();
        movieBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_ValidateMovieRequest_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.movie.ValidateMovieRequest getDefaultInstanceForType() {
      return com.movieplatform.proto.movie.ValidateMovieRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.movie.ValidateMovieRequest build() {
      com.movieplatform.proto.movie.ValidateMovieRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.movie.ValidateMovieRequest buildPartial() {
      com.movieplatform.proto.movie.ValidateMovieRequest result = new com.movieplatform.proto.movie.ValidateMovieRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.movieplatform.proto.movie.ValidateMovieRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseRequest_ = baseRequestBuilder_ == null
            ? baseRequest_
            : baseRequestBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.movie_ = movieBuilder_ == null
            ? movie_
            : movieBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.movie.ValidateMovieRequest) {
        return mergeFrom((com.movieplatform.proto.movie.ValidateMovieRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.movie.ValidateMovieRequest other) {
      if (other == com.movieplatform.proto.movie.ValidateMovieRequest.getDefaultInstance()) return this;
      if (other.hasBaseRequest()) {
        mergeBaseRequest(other.getBaseRequest());
      }
      if (other.hasMovie()) {
        mergeMovie(other.getMovie());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBaseRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMovieFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.movieplatform.proto.common.BaseRequest baseRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.BaseRequest, com.movieplatform.proto.common.BaseRequest.Builder, com.movieplatform.proto.common.BaseRequestOrBuilder> baseRequestBuilder_;
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     * @return Whether the baseRequest field is set.
     */
    public boolean hasBaseRequest() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     * @return The baseRequest.
     */
    public com.movieplatform.proto.common.BaseRequest getBaseRequest() {
      if (baseRequestBuilder_ == null) {
        return baseRequest_ == null ? com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
      } else {
        return baseRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder setBaseRequest(com.movieplatform.proto.common.BaseRequest value) {
      if (baseRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseRequest_ = value;
      } else {
        baseRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder setBaseRequest(
        com.movieplatform.proto.common.BaseRequest.Builder builderForValue) {
      if (baseRequestBuilder_ == null) {
        baseRequest_ = builderForValue.build();
      } else {
        baseRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder mergeBaseRequest(com.movieplatform.proto.common.BaseRequest value) {
      if (baseRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseRequest_ != null &&
          baseRequest_ != com.movieplatform.proto.common.BaseRequest.getDefaultInstance()) {
          getBaseRequestBuilder().mergeFrom(value);
        } else {
          baseRequest_ = value;
        }
      } else {
        baseRequestBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder clearBaseRequest() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseRequest_ = null;
      if (baseRequestBuilder_ != null) {
        baseRequestBuilder_.dispose();
        baseRequestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public com.movieplatform.proto.common.BaseRequest.Builder getBaseRequestBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBaseRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public com.movieplatform.proto.common.BaseRequestOrBuilder getBaseRequestOrBuilder() {
      if (baseRequestBuilder_ != null) {
        return baseRequestBuilder_.getMessageOrBuilder();
      } else {
        return baseRequest_ == null ?
            com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
      }
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.BaseRequest, com.movieplatform.proto.common.BaseRequest.Builder, com.movieplatform.proto.common.BaseRequestOrBuilder> 
        getBaseRequestFieldBuilder() {
      if (baseRequestBuilder_ == null) {
        baseRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.movieplatform.proto.common.BaseRequest, com.movieplatform.proto.common.BaseRequest.Builder, com.movieplatform.proto.common.BaseRequestOrBuilder>(
                getBaseRequest(),
                getParentForChildren(),
                isClean());
        baseRequest_ = null;
      }
      return baseRequestBuilder_;
    }

    private com.movieplatform.proto.movie.Movie movie_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.movie.Movie, com.movieplatform.proto.movie.Movie.Builder, com.movieplatform.proto.movie.MovieOrBuilder> movieBuilder_;
    /**
     * <pre>
     * Movie to validate
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     * @return Whether the movie field is set.
     */
    public boolean hasMovie() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Movie to validate
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     * @return The movie.
     */
    public com.movieplatform.proto.movie.Movie getMovie() {
      if (movieBuilder_ == null) {
        return movie_ == null ? com.movieplatform.proto.movie.Movie.getDefaultInstance() : movie_;
      } else {
        return movieBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Movie to validate
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    public Builder setMovie(com.movieplatform.proto.movie.Movie value) {
      if (movieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        movie_ = value;
      } else {
        movieBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Movie to validate
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    public Builder setMovie(
        com.movieplatform.proto.movie.Movie.Builder builderForValue) {
      if (movieBuilder_ == null) {
        movie_ = builderForValue.build();
      } else {
        movieBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Movie to validate
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    public Builder mergeMovie(com.movieplatform.proto.movie.Movie value) {
      if (movieBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          movie_ != null &&
          movie_ != com.movieplatform.proto.movie.Movie.getDefaultInstance()) {
          getMovieBuilder().mergeFrom(value);
        } else {
          movie_ = value;
        }
      } else {
        movieBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Movie to validate
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    public Builder clearMovie() {
      bitField0_ = (bitField0_ & ~0x00000002);
      movie_ = null;
      if (movieBuilder_ != null) {
        movieBuilder_.dispose();
        movieBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Movie to validate
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    public com.movieplatform.proto.movie.Movie.Builder getMovieBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMovieFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Movie to validate
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    public com.movieplatform.proto.movie.MovieOrBuilder getMovieOrBuilder() {
      if (movieBuilder_ != null) {
        return movieBuilder_.getMessageOrBuilder();
      } else {
        return movie_ == null ?
            com.movieplatform.proto.movie.Movie.getDefaultInstance() : movie_;
      }
    }
    /**
     * <pre>
     * Movie to validate
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.movie.Movie, com.movieplatform.proto.movie.Movie.Builder, com.movieplatform.proto.movie.MovieOrBuilder> 
        getMovieFieldBuilder() {
      if (movieBuilder_ == null) {
        movieBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.movieplatform.proto.movie.Movie, com.movieplatform.proto.movie.Movie.Builder, com.movieplatform.proto.movie.MovieOrBuilder>(
                getMovie(),
                getParentForChildren(),
                isClean());
        movie_ = null;
      }
      return movieBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.movie.ValidateMovieRequest)
  }

  // @@protoc_insertion_point(class_scope:proto.movie.ValidateMovieRequest)
  private static final com.movieplatform.proto.movie.ValidateMovieRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.movie.ValidateMovieRequest();
  }

  public static com.movieplatform.proto.movie.ValidateMovieRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValidateMovieRequest>
      PARSER = new com.google.protobuf.AbstractParser<ValidateMovieRequest>() {
    @java.lang.Override
    public ValidateMovieRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ValidateMovieRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValidateMovieRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.movie.ValidateMovieRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

