// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification/notification_req_res.proto

package com.movieplatform.proto.notification;

/**
 * <pre>
 * Delivery report
 * </pre>
 *
 * Protobuf type {@code proto.notification.DeliveryReport}
 */
public final class DeliveryReport extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.notification.DeliveryReport)
    DeliveryReportOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeliveryReport.newBuilder() to construct.
  private DeliveryReport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeliveryReport() {
    reportId_ = "";
    notificationType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeliveryReport();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_DeliveryReport_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_DeliveryReport_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.notification.DeliveryReport.class, com.movieplatform.proto.notification.DeliveryReport.Builder.class);
  }

  public static final int REPORT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reportId_ = "";
  /**
   * <pre>
   * Report ID
   * </pre>
   *
   * <code>string report_id = 1;</code>
   * @return The reportId.
   */
  @java.lang.Override
  public java.lang.String getReportId() {
    java.lang.Object ref = reportId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reportId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Report ID
   * </pre>
   *
   * <code>string report_id = 1;</code>
   * @return The bytes for reportId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReportIdBytes() {
    java.lang.Object ref = reportId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reportId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTIFICATION_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object notificationType_ = "";
  /**
   * <pre>
   * Notification type
   * </pre>
   *
   * <code>string notification_type = 2;</code>
   * @return The notificationType.
   */
  @java.lang.Override
  public java.lang.String getNotificationType() {
    java.lang.Object ref = notificationType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notificationType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Notification type
   * </pre>
   *
   * <code>string notification_type = 2;</code>
   * @return The bytes for notificationType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNotificationTypeBytes() {
    java.lang.Object ref = notificationType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notificationType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_SENT_FIELD_NUMBER = 3;
  private int totalSent_ = 0;
  /**
   * <pre>
   * Total sent
   * </pre>
   *
   * <code>int32 total_sent = 3;</code>
   * @return The totalSent.
   */
  @java.lang.Override
  public int getTotalSent() {
    return totalSent_;
  }

  public static final int DELIVERED_FIELD_NUMBER = 4;
  private int delivered_ = 0;
  /**
   * <pre>
   * Delivered count
   * </pre>
   *
   * <code>int32 delivered = 4;</code>
   * @return The delivered.
   */
  @java.lang.Override
  public int getDelivered() {
    return delivered_;
  }

  public static final int FAILED_FIELD_NUMBER = 5;
  private int failed_ = 0;
  /**
   * <pre>
   * Failed count
   * </pre>
   *
   * <code>int32 failed = 5;</code>
   * @return The failed.
   */
  @java.lang.Override
  public int getFailed() {
    return failed_;
  }

  public static final int OPENED_FIELD_NUMBER = 6;
  private int opened_ = 0;
  /**
   * <pre>
   * Opened count
   * </pre>
   *
   * <code>int32 opened = 6;</code>
   * @return The opened.
   */
  @java.lang.Override
  public int getOpened() {
    return opened_;
  }

  public static final int CLICKED_FIELD_NUMBER = 7;
  private int clicked_ = 0;
  /**
   * <pre>
   * Clicked count
   * </pre>
   *
   * <code>int32 clicked = 7;</code>
   * @return The clicked.
   */
  @java.lang.Override
  public int getClicked() {
    return clicked_;
  }

  public static final int DELIVERY_RATE_FIELD_NUMBER = 8;
  private float deliveryRate_ = 0F;
  /**
   * <pre>
   * Delivery rate percentage
   * </pre>
   *
   * <code>float delivery_rate = 8;</code>
   * @return The deliveryRate.
   */
  @java.lang.Override
  public float getDeliveryRate() {
    return deliveryRate_;
  }

  public static final int OPEN_RATE_FIELD_NUMBER = 9;
  private float openRate_ = 0F;
  /**
   * <pre>
   * Open rate percentage
   * </pre>
   *
   * <code>float open_rate = 9;</code>
   * @return The openRate.
   */
  @java.lang.Override
  public float getOpenRate() {
    return openRate_;
  }

  public static final int CLICK_RATE_FIELD_NUMBER = 10;
  private float clickRate_ = 0F;
  /**
   * <pre>
   * Click rate percentage
   * </pre>
   *
   * <code>float click_rate = 10;</code>
   * @return The clickRate.
   */
  @java.lang.Override
  public float getClickRate() {
    return clickRate_;
  }

  public static final int REPORT_DATE_FIELD_NUMBER = 11;
  private com.movieplatform.proto.common.DateTime reportDate_;
  /**
   * <pre>
   * Report date
   * </pre>
   *
   * <code>.proto.common.DateTime report_date = 11;</code>
   * @return Whether the reportDate field is set.
   */
  @java.lang.Override
  public boolean hasReportDate() {
    return reportDate_ != null;
  }
  /**
   * <pre>
   * Report date
   * </pre>
   *
   * <code>.proto.common.DateTime report_date = 11;</code>
   * @return The reportDate.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTime getReportDate() {
    return reportDate_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : reportDate_;
  }
  /**
   * <pre>
   * Report date
   * </pre>
   *
   * <code>.proto.common.DateTime report_date = 11;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTimeOrBuilder getReportDateOrBuilder() {
    return reportDate_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : reportDate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reportId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reportId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(notificationType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, notificationType_);
    }
    if (totalSent_ != 0) {
      output.writeInt32(3, totalSent_);
    }
    if (delivered_ != 0) {
      output.writeInt32(4, delivered_);
    }
    if (failed_ != 0) {
      output.writeInt32(5, failed_);
    }
    if (opened_ != 0) {
      output.writeInt32(6, opened_);
    }
    if (clicked_ != 0) {
      output.writeInt32(7, clicked_);
    }
    if (java.lang.Float.floatToRawIntBits(deliveryRate_) != 0) {
      output.writeFloat(8, deliveryRate_);
    }
    if (java.lang.Float.floatToRawIntBits(openRate_) != 0) {
      output.writeFloat(9, openRate_);
    }
    if (java.lang.Float.floatToRawIntBits(clickRate_) != 0) {
      output.writeFloat(10, clickRate_);
    }
    if (reportDate_ != null) {
      output.writeMessage(11, getReportDate());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reportId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reportId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(notificationType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, notificationType_);
    }
    if (totalSent_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalSent_);
    }
    if (delivered_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, delivered_);
    }
    if (failed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, failed_);
    }
    if (opened_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, opened_);
    }
    if (clicked_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, clicked_);
    }
    if (java.lang.Float.floatToRawIntBits(deliveryRate_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(8, deliveryRate_);
    }
    if (java.lang.Float.floatToRawIntBits(openRate_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(9, openRate_);
    }
    if (java.lang.Float.floatToRawIntBits(clickRate_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(10, clickRate_);
    }
    if (reportDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getReportDate());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.notification.DeliveryReport)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.notification.DeliveryReport other = (com.movieplatform.proto.notification.DeliveryReport) obj;

    if (!getReportId()
        .equals(other.getReportId())) return false;
    if (!getNotificationType()
        .equals(other.getNotificationType())) return false;
    if (getTotalSent()
        != other.getTotalSent()) return false;
    if (getDelivered()
        != other.getDelivered()) return false;
    if (getFailed()
        != other.getFailed()) return false;
    if (getOpened()
        != other.getOpened()) return false;
    if (getClicked()
        != other.getClicked()) return false;
    if (java.lang.Float.floatToIntBits(getDeliveryRate())
        != java.lang.Float.floatToIntBits(
            other.getDeliveryRate())) return false;
    if (java.lang.Float.floatToIntBits(getOpenRate())
        != java.lang.Float.floatToIntBits(
            other.getOpenRate())) return false;
    if (java.lang.Float.floatToIntBits(getClickRate())
        != java.lang.Float.floatToIntBits(
            other.getClickRate())) return false;
    if (hasReportDate() != other.hasReportDate()) return false;
    if (hasReportDate()) {
      if (!getReportDate()
          .equals(other.getReportDate())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPORT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReportId().hashCode();
    hash = (37 * hash) + NOTIFICATION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getNotificationType().hashCode();
    hash = (37 * hash) + TOTAL_SENT_FIELD_NUMBER;
    hash = (53 * hash) + getTotalSent();
    hash = (37 * hash) + DELIVERED_FIELD_NUMBER;
    hash = (53 * hash) + getDelivered();
    hash = (37 * hash) + FAILED_FIELD_NUMBER;
    hash = (53 * hash) + getFailed();
    hash = (37 * hash) + OPENED_FIELD_NUMBER;
    hash = (53 * hash) + getOpened();
    hash = (37 * hash) + CLICKED_FIELD_NUMBER;
    hash = (53 * hash) + getClicked();
    hash = (37 * hash) + DELIVERY_RATE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDeliveryRate());
    hash = (37 * hash) + OPEN_RATE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getOpenRate());
    hash = (37 * hash) + CLICK_RATE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getClickRate());
    if (hasReportDate()) {
      hash = (37 * hash) + REPORT_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getReportDate().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.notification.DeliveryReport parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.DeliveryReport parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.DeliveryReport parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.DeliveryReport parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.DeliveryReport parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.DeliveryReport parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.DeliveryReport parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.notification.DeliveryReport parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.DeliveryReport parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.notification.DeliveryReport parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.DeliveryReport parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.notification.DeliveryReport parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.notification.DeliveryReport prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Delivery report
   * </pre>
   *
   * Protobuf type {@code proto.notification.DeliveryReport}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.notification.DeliveryReport)
      com.movieplatform.proto.notification.DeliveryReportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_DeliveryReport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_DeliveryReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.notification.DeliveryReport.class, com.movieplatform.proto.notification.DeliveryReport.Builder.class);
    }

    // Construct using com.movieplatform.proto.notification.DeliveryReport.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      reportId_ = "";
      notificationType_ = "";
      totalSent_ = 0;
      delivered_ = 0;
      failed_ = 0;
      opened_ = 0;
      clicked_ = 0;
      deliveryRate_ = 0F;
      openRate_ = 0F;
      clickRate_ = 0F;
      reportDate_ = null;
      if (reportDateBuilder_ != null) {
        reportDateBuilder_.dispose();
        reportDateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_DeliveryReport_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.DeliveryReport getDefaultInstanceForType() {
      return com.movieplatform.proto.notification.DeliveryReport.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.DeliveryReport build() {
      com.movieplatform.proto.notification.DeliveryReport result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.DeliveryReport buildPartial() {
      com.movieplatform.proto.notification.DeliveryReport result = new com.movieplatform.proto.notification.DeliveryReport(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.movieplatform.proto.notification.DeliveryReport result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.reportId_ = reportId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.notificationType_ = notificationType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalSent_ = totalSent_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.delivered_ = delivered_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.failed_ = failed_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.opened_ = opened_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.clicked_ = clicked_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.deliveryRate_ = deliveryRate_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.openRate_ = openRate_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.clickRate_ = clickRate_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.reportDate_ = reportDateBuilder_ == null
            ? reportDate_
            : reportDateBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.notification.DeliveryReport) {
        return mergeFrom((com.movieplatform.proto.notification.DeliveryReport)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.notification.DeliveryReport other) {
      if (other == com.movieplatform.proto.notification.DeliveryReport.getDefaultInstance()) return this;
      if (!other.getReportId().isEmpty()) {
        reportId_ = other.reportId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getNotificationType().isEmpty()) {
        notificationType_ = other.notificationType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getTotalSent() != 0) {
        setTotalSent(other.getTotalSent());
      }
      if (other.getDelivered() != 0) {
        setDelivered(other.getDelivered());
      }
      if (other.getFailed() != 0) {
        setFailed(other.getFailed());
      }
      if (other.getOpened() != 0) {
        setOpened(other.getOpened());
      }
      if (other.getClicked() != 0) {
        setClicked(other.getClicked());
      }
      if (other.getDeliveryRate() != 0F) {
        setDeliveryRate(other.getDeliveryRate());
      }
      if (other.getOpenRate() != 0F) {
        setOpenRate(other.getOpenRate());
      }
      if (other.getClickRate() != 0F) {
        setClickRate(other.getClickRate());
      }
      if (other.hasReportDate()) {
        mergeReportDate(other.getReportDate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              reportId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              notificationType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              totalSent_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              delivered_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              failed_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              opened_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              clicked_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 69: {
              deliveryRate_ = input.readFloat();
              bitField0_ |= 0x00000080;
              break;
            } // case 69
            case 77: {
              openRate_ = input.readFloat();
              bitField0_ |= 0x00000100;
              break;
            } // case 77
            case 85: {
              clickRate_ = input.readFloat();
              bitField0_ |= 0x00000200;
              break;
            } // case 85
            case 90: {
              input.readMessage(
                  getReportDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object reportId_ = "";
    /**
     * <pre>
     * Report ID
     * </pre>
     *
     * <code>string report_id = 1;</code>
     * @return The reportId.
     */
    public java.lang.String getReportId() {
      java.lang.Object ref = reportId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reportId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Report ID
     * </pre>
     *
     * <code>string report_id = 1;</code>
     * @return The bytes for reportId.
     */
    public com.google.protobuf.ByteString
        getReportIdBytes() {
      java.lang.Object ref = reportId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reportId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Report ID
     * </pre>
     *
     * <code>string report_id = 1;</code>
     * @param value The reportId to set.
     * @return This builder for chaining.
     */
    public Builder setReportId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reportId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Report ID
     * </pre>
     *
     * <code>string report_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReportId() {
      reportId_ = getDefaultInstance().getReportId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Report ID
     * </pre>
     *
     * <code>string report_id = 1;</code>
     * @param value The bytes for reportId to set.
     * @return This builder for chaining.
     */
    public Builder setReportIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reportId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object notificationType_ = "";
    /**
     * <pre>
     * Notification type
     * </pre>
     *
     * <code>string notification_type = 2;</code>
     * @return The notificationType.
     */
    public java.lang.String getNotificationType() {
      java.lang.Object ref = notificationType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notificationType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Notification type
     * </pre>
     *
     * <code>string notification_type = 2;</code>
     * @return The bytes for notificationType.
     */
    public com.google.protobuf.ByteString
        getNotificationTypeBytes() {
      java.lang.Object ref = notificationType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notificationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Notification type
     * </pre>
     *
     * <code>string notification_type = 2;</code>
     * @param value The notificationType to set.
     * @return This builder for chaining.
     */
    public Builder setNotificationType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      notificationType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Notification type
     * </pre>
     *
     * <code>string notification_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNotificationType() {
      notificationType_ = getDefaultInstance().getNotificationType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Notification type
     * </pre>
     *
     * <code>string notification_type = 2;</code>
     * @param value The bytes for notificationType to set.
     * @return This builder for chaining.
     */
    public Builder setNotificationTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      notificationType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int totalSent_ ;
    /**
     * <pre>
     * Total sent
     * </pre>
     *
     * <code>int32 total_sent = 3;</code>
     * @return The totalSent.
     */
    @java.lang.Override
    public int getTotalSent() {
      return totalSent_;
    }
    /**
     * <pre>
     * Total sent
     * </pre>
     *
     * <code>int32 total_sent = 3;</code>
     * @param value The totalSent to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSent(int value) {
      
      totalSent_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total sent
     * </pre>
     *
     * <code>int32 total_sent = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalSent() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalSent_ = 0;
      onChanged();
      return this;
    }

    private int delivered_ ;
    /**
     * <pre>
     * Delivered count
     * </pre>
     *
     * <code>int32 delivered = 4;</code>
     * @return The delivered.
     */
    @java.lang.Override
    public int getDelivered() {
      return delivered_;
    }
    /**
     * <pre>
     * Delivered count
     * </pre>
     *
     * <code>int32 delivered = 4;</code>
     * @param value The delivered to set.
     * @return This builder for chaining.
     */
    public Builder setDelivered(int value) {
      
      delivered_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Delivered count
     * </pre>
     *
     * <code>int32 delivered = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDelivered() {
      bitField0_ = (bitField0_ & ~0x00000008);
      delivered_ = 0;
      onChanged();
      return this;
    }

    private int failed_ ;
    /**
     * <pre>
     * Failed count
     * </pre>
     *
     * <code>int32 failed = 5;</code>
     * @return The failed.
     */
    @java.lang.Override
    public int getFailed() {
      return failed_;
    }
    /**
     * <pre>
     * Failed count
     * </pre>
     *
     * <code>int32 failed = 5;</code>
     * @param value The failed to set.
     * @return This builder for chaining.
     */
    public Builder setFailed(int value) {
      
      failed_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Failed count
     * </pre>
     *
     * <code>int32 failed = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFailed() {
      bitField0_ = (bitField0_ & ~0x00000010);
      failed_ = 0;
      onChanged();
      return this;
    }

    private int opened_ ;
    /**
     * <pre>
     * Opened count
     * </pre>
     *
     * <code>int32 opened = 6;</code>
     * @return The opened.
     */
    @java.lang.Override
    public int getOpened() {
      return opened_;
    }
    /**
     * <pre>
     * Opened count
     * </pre>
     *
     * <code>int32 opened = 6;</code>
     * @param value The opened to set.
     * @return This builder for chaining.
     */
    public Builder setOpened(int value) {
      
      opened_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Opened count
     * </pre>
     *
     * <code>int32 opened = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpened() {
      bitField0_ = (bitField0_ & ~0x00000020);
      opened_ = 0;
      onChanged();
      return this;
    }

    private int clicked_ ;
    /**
     * <pre>
     * Clicked count
     * </pre>
     *
     * <code>int32 clicked = 7;</code>
     * @return The clicked.
     */
    @java.lang.Override
    public int getClicked() {
      return clicked_;
    }
    /**
     * <pre>
     * Clicked count
     * </pre>
     *
     * <code>int32 clicked = 7;</code>
     * @param value The clicked to set.
     * @return This builder for chaining.
     */
    public Builder setClicked(int value) {
      
      clicked_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Clicked count
     * </pre>
     *
     * <code>int32 clicked = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearClicked() {
      bitField0_ = (bitField0_ & ~0x00000040);
      clicked_ = 0;
      onChanged();
      return this;
    }

    private float deliveryRate_ ;
    /**
     * <pre>
     * Delivery rate percentage
     * </pre>
     *
     * <code>float delivery_rate = 8;</code>
     * @return The deliveryRate.
     */
    @java.lang.Override
    public float getDeliveryRate() {
      return deliveryRate_;
    }
    /**
     * <pre>
     * Delivery rate percentage
     * </pre>
     *
     * <code>float delivery_rate = 8;</code>
     * @param value The deliveryRate to set.
     * @return This builder for chaining.
     */
    public Builder setDeliveryRate(float value) {
      
      deliveryRate_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Delivery rate percentage
     * </pre>
     *
     * <code>float delivery_rate = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeliveryRate() {
      bitField0_ = (bitField0_ & ~0x00000080);
      deliveryRate_ = 0F;
      onChanged();
      return this;
    }

    private float openRate_ ;
    /**
     * <pre>
     * Open rate percentage
     * </pre>
     *
     * <code>float open_rate = 9;</code>
     * @return The openRate.
     */
    @java.lang.Override
    public float getOpenRate() {
      return openRate_;
    }
    /**
     * <pre>
     * Open rate percentage
     * </pre>
     *
     * <code>float open_rate = 9;</code>
     * @param value The openRate to set.
     * @return This builder for chaining.
     */
    public Builder setOpenRate(float value) {
      
      openRate_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Open rate percentage
     * </pre>
     *
     * <code>float open_rate = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpenRate() {
      bitField0_ = (bitField0_ & ~0x00000100);
      openRate_ = 0F;
      onChanged();
      return this;
    }

    private float clickRate_ ;
    /**
     * <pre>
     * Click rate percentage
     * </pre>
     *
     * <code>float click_rate = 10;</code>
     * @return The clickRate.
     */
    @java.lang.Override
    public float getClickRate() {
      return clickRate_;
    }
    /**
     * <pre>
     * Click rate percentage
     * </pre>
     *
     * <code>float click_rate = 10;</code>
     * @param value The clickRate to set.
     * @return This builder for chaining.
     */
    public Builder setClickRate(float value) {
      
      clickRate_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Click rate percentage
     * </pre>
     *
     * <code>float click_rate = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearClickRate() {
      bitField0_ = (bitField0_ & ~0x00000200);
      clickRate_ = 0F;
      onChanged();
      return this;
    }

    private com.movieplatform.proto.common.DateTime reportDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> reportDateBuilder_;
    /**
     * <pre>
     * Report date
     * </pre>
     *
     * <code>.proto.common.DateTime report_date = 11;</code>
     * @return Whether the reportDate field is set.
     */
    public boolean hasReportDate() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <pre>
     * Report date
     * </pre>
     *
     * <code>.proto.common.DateTime report_date = 11;</code>
     * @return The reportDate.
     */
    public com.movieplatform.proto.common.DateTime getReportDate() {
      if (reportDateBuilder_ == null) {
        return reportDate_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : reportDate_;
      } else {
        return reportDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Report date
     * </pre>
     *
     * <code>.proto.common.DateTime report_date = 11;</code>
     */
    public Builder setReportDate(com.movieplatform.proto.common.DateTime value) {
      if (reportDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reportDate_ = value;
      } else {
        reportDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Report date
     * </pre>
     *
     * <code>.proto.common.DateTime report_date = 11;</code>
     */
    public Builder setReportDate(
        com.movieplatform.proto.common.DateTime.Builder builderForValue) {
      if (reportDateBuilder_ == null) {
        reportDate_ = builderForValue.build();
      } else {
        reportDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Report date
     * </pre>
     *
     * <code>.proto.common.DateTime report_date = 11;</code>
     */
    public Builder mergeReportDate(com.movieplatform.proto.common.DateTime value) {
      if (reportDateBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
          reportDate_ != null &&
          reportDate_ != com.movieplatform.proto.common.DateTime.getDefaultInstance()) {
          getReportDateBuilder().mergeFrom(value);
        } else {
          reportDate_ = value;
        }
      } else {
        reportDateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Report date
     * </pre>
     *
     * <code>.proto.common.DateTime report_date = 11;</code>
     */
    public Builder clearReportDate() {
      bitField0_ = (bitField0_ & ~0x00000400);
      reportDate_ = null;
      if (reportDateBuilder_ != null) {
        reportDateBuilder_.dispose();
        reportDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Report date
     * </pre>
     *
     * <code>.proto.common.DateTime report_date = 11;</code>
     */
    public com.movieplatform.proto.common.DateTime.Builder getReportDateBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getReportDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Report date
     * </pre>
     *
     * <code>.proto.common.DateTime report_date = 11;</code>
     */
    public com.movieplatform.proto.common.DateTimeOrBuilder getReportDateOrBuilder() {
      if (reportDateBuilder_ != null) {
        return reportDateBuilder_.getMessageOrBuilder();
      } else {
        return reportDate_ == null ?
            com.movieplatform.proto.common.DateTime.getDefaultInstance() : reportDate_;
      }
    }
    /**
     * <pre>
     * Report date
     * </pre>
     *
     * <code>.proto.common.DateTime report_date = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> 
        getReportDateFieldBuilder() {
      if (reportDateBuilder_ == null) {
        reportDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder>(
                getReportDate(),
                getParentForChildren(),
                isClean());
        reportDate_ = null;
      }
      return reportDateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.notification.DeliveryReport)
  }

  // @@protoc_insertion_point(class_scope:proto.notification.DeliveryReport)
  private static final com.movieplatform.proto.notification.DeliveryReport DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.notification.DeliveryReport();
  }

  public static com.movieplatform.proto.notification.DeliveryReport getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeliveryReport>
      PARSER = new com.google.protobuf.AbstractParser<DeliveryReport>() {
    @java.lang.Override
    public DeliveryReport parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeliveryReport> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeliveryReport> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.notification.DeliveryReport getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

