// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification/notification_req_res.proto

package com.movieplatform.proto.notification;

public interface EngagementEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.notification.EngagementEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Event ID
   * </pre>
   *
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <pre>
   * Event ID
   * </pre>
   *
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <pre>
   * User ID
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * User ID
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * Notification ID
   * </pre>
   *
   * <code>string notification_id = 3;</code>
   * @return The notificationId.
   */
  java.lang.String getNotificationId();
  /**
   * <pre>
   * Notification ID
   * </pre>
   *
   * <code>string notification_id = 3;</code>
   * @return The bytes for notificationId.
   */
  com.google.protobuf.ByteString
      getNotificationIdBytes();

  /**
   * <pre>
   * Event type
   * </pre>
   *
   * <code>string event_type = 4;</code>
   * @return The eventType.
   */
  java.lang.String getEventType();
  /**
   * <pre>
   * Event type
   * </pre>
   *
   * <code>string event_type = 4;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <pre>
   * When event occurred
   * </pre>
   *
   * <code>.proto.common.DateTime event_time = 5;</code>
   * @return Whether the eventTime field is set.
   */
  boolean hasEventTime();
  /**
   * <pre>
   * When event occurred
   * </pre>
   *
   * <code>.proto.common.DateTime event_time = 5;</code>
   * @return The eventTime.
   */
  com.movieplatform.proto.common.DateTime getEventTime();
  /**
   * <pre>
   * When event occurred
   * </pre>
   *
   * <code>.proto.common.DateTime event_time = 5;</code>
   */
  com.movieplatform.proto.common.DateTimeOrBuilder getEventTimeOrBuilder();

  /**
   * <pre>
   * Event-specific data
   * </pre>
   *
   * <code>map&lt;string, string&gt; event_data = 6;</code>
   */
  int getEventDataCount();
  /**
   * <pre>
   * Event-specific data
   * </pre>
   *
   * <code>map&lt;string, string&gt; event_data = 6;</code>
   */
  boolean containsEventData(
      java.lang.String key);
  /**
   * Use {@link #getEventDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getEventData();
  /**
   * <pre>
   * Event-specific data
   * </pre>
   *
   * <code>map&lt;string, string&gt; event_data = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getEventDataMap();
  /**
   * <pre>
   * Event-specific data
   * </pre>
   *
   * <code>map&lt;string, string&gt; event_data = 6;</code>
   */
  /* nullable */
java.lang.String getEventDataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * Event-specific data
   * </pre>
   *
   * <code>map&lt;string, string&gt; event_data = 6;</code>
   */
  java.lang.String getEventDataOrThrow(
      java.lang.String key);
}
