// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification/notification_req_res.proto

package com.movieplatform.proto.notification;

/**
 * <pre>
 * Engagement event
 * </pre>
 *
 * Protobuf type {@code proto.notification.EngagementEvent}
 */
public final class EngagementEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.notification.EngagementEvent)
    EngagementEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EngagementEvent.newBuilder() to construct.
  private EngagementEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EngagementEvent() {
    eventId_ = "";
    userId_ = "";
    notificationId_ = "";
    eventType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EngagementEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_EngagementEvent_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetEventData();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_EngagementEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.notification.EngagementEvent.class, com.movieplatform.proto.notification.EngagementEvent.Builder.class);
  }

  public static final int EVENT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventId_ = "";
  /**
   * <pre>
   * Event ID
   * </pre>
   *
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  @java.lang.Override
  public java.lang.String getEventId() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Event ID
   * </pre>
   *
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventIdBytes() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userId_ = "";
  /**
   * <pre>
   * User ID
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * User ID
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTIFICATION_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object notificationId_ = "";
  /**
   * <pre>
   * Notification ID
   * </pre>
   *
   * <code>string notification_id = 3;</code>
   * @return The notificationId.
   */
  @java.lang.Override
  public java.lang.String getNotificationId() {
    java.lang.Object ref = notificationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notificationId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Notification ID
   * </pre>
   *
   * <code>string notification_id = 3;</code>
   * @return The bytes for notificationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNotificationIdBytes() {
    java.lang.Object ref = notificationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notificationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventType_ = "";
  /**
   * <pre>
   * Event type
   * </pre>
   *
   * <code>string event_type = 4;</code>
   * @return The eventType.
   */
  @java.lang.Override
  public java.lang.String getEventType() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Event type
   * </pre>
   *
   * <code>string event_type = 4;</code>
   * @return The bytes for eventType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventTypeBytes() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_TIME_FIELD_NUMBER = 5;
  private com.movieplatform.proto.common.DateTime eventTime_;
  /**
   * <pre>
   * When event occurred
   * </pre>
   *
   * <code>.proto.common.DateTime event_time = 5;</code>
   * @return Whether the eventTime field is set.
   */
  @java.lang.Override
  public boolean hasEventTime() {
    return eventTime_ != null;
  }
  /**
   * <pre>
   * When event occurred
   * </pre>
   *
   * <code>.proto.common.DateTime event_time = 5;</code>
   * @return The eventTime.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTime getEventTime() {
    return eventTime_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : eventTime_;
  }
  /**
   * <pre>
   * When event occurred
   * </pre>
   *
   * <code>.proto.common.DateTime event_time = 5;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTimeOrBuilder getEventTimeOrBuilder() {
    return eventTime_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : eventTime_;
  }

  public static final int EVENT_DATA_FIELD_NUMBER = 6;
  private static final class EventDataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_EngagementEvent_EventDataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> eventData_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetEventData() {
    if (eventData_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          EventDataDefaultEntryHolder.defaultEntry);
    }
    return eventData_;
  }
  public int getEventDataCount() {
    return internalGetEventData().getMap().size();
  }
  /**
   * <pre>
   * Event-specific data
   * </pre>
   *
   * <code>map&lt;string, string&gt; event_data = 6;</code>
   */
  @java.lang.Override
  public boolean containsEventData(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetEventData().getMap().containsKey(key);
  }
  /**
   * Use {@link #getEventDataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getEventData() {
    return getEventDataMap();
  }
  /**
   * <pre>
   * Event-specific data
   * </pre>
   *
   * <code>map&lt;string, string&gt; event_data = 6;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getEventDataMap() {
    return internalGetEventData().getMap();
  }
  /**
   * <pre>
   * Event-specific data
   * </pre>
   *
   * <code>map&lt;string, string&gt; event_data = 6;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getEventDataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetEventData().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Event-specific data
   * </pre>
   *
   * <code>map&lt;string, string&gt; event_data = 6;</code>
   */
  @java.lang.Override
  public java.lang.String getEventDataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetEventData().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(notificationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, notificationId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, eventType_);
    }
    if (eventTime_ != null) {
      output.writeMessage(5, getEventTime());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetEventData(),
        EventDataDefaultEntryHolder.defaultEntry,
        6);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(notificationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, notificationId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, eventType_);
    }
    if (eventTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getEventTime());
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetEventData().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      eventData__ = EventDataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, eventData__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.notification.EngagementEvent)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.notification.EngagementEvent other = (com.movieplatform.proto.notification.EngagementEvent) obj;

    if (!getEventId()
        .equals(other.getEventId())) return false;
    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getNotificationId()
        .equals(other.getNotificationId())) return false;
    if (!getEventType()
        .equals(other.getEventType())) return false;
    if (hasEventTime() != other.hasEventTime()) return false;
    if (hasEventTime()) {
      if (!getEventTime()
          .equals(other.getEventTime())) return false;
    }
    if (!internalGetEventData().equals(
        other.internalGetEventData())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEventId().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + NOTIFICATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getNotificationId().hashCode();
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEventType().hashCode();
    if (hasEventTime()) {
      hash = (37 * hash) + EVENT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getEventTime().hashCode();
    }
    if (!internalGetEventData().getMap().isEmpty()) {
      hash = (37 * hash) + EVENT_DATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetEventData().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.notification.EngagementEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.EngagementEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.EngagementEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.EngagementEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.EngagementEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.EngagementEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.EngagementEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.notification.EngagementEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.EngagementEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.notification.EngagementEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.EngagementEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.notification.EngagementEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.notification.EngagementEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Engagement event
   * </pre>
   *
   * Protobuf type {@code proto.notification.EngagementEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.notification.EngagementEvent)
      com.movieplatform.proto.notification.EngagementEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_EngagementEvent_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetEventData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableEventData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_EngagementEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.notification.EngagementEvent.class, com.movieplatform.proto.notification.EngagementEvent.Builder.class);
    }

    // Construct using com.movieplatform.proto.notification.EngagementEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventId_ = "";
      userId_ = "";
      notificationId_ = "";
      eventType_ = "";
      eventTime_ = null;
      if (eventTimeBuilder_ != null) {
        eventTimeBuilder_.dispose();
        eventTimeBuilder_ = null;
      }
      internalGetMutableEventData().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_EngagementEvent_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.EngagementEvent getDefaultInstanceForType() {
      return com.movieplatform.proto.notification.EngagementEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.EngagementEvent build() {
      com.movieplatform.proto.notification.EngagementEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.EngagementEvent buildPartial() {
      com.movieplatform.proto.notification.EngagementEvent result = new com.movieplatform.proto.notification.EngagementEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.movieplatform.proto.notification.EngagementEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.eventId_ = eventId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.notificationId_ = notificationId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.eventType_ = eventType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.eventTime_ = eventTimeBuilder_ == null
            ? eventTime_
            : eventTimeBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.eventData_ = internalGetEventData();
        result.eventData_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.notification.EngagementEvent) {
        return mergeFrom((com.movieplatform.proto.notification.EngagementEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.notification.EngagementEvent other) {
      if (other == com.movieplatform.proto.notification.EngagementEvent.getDefaultInstance()) return this;
      if (!other.getEventId().isEmpty()) {
        eventId_ = other.eventId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getNotificationId().isEmpty()) {
        notificationId_ = other.notificationId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getEventType().isEmpty()) {
        eventType_ = other.eventType_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasEventTime()) {
        mergeEventTime(other.getEventTime());
      }
      internalGetMutableEventData().mergeFrom(
          other.internalGetEventData());
      bitField0_ |= 0x00000020;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              eventId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              notificationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              eventType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getEventTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              eventData__ = input.readMessage(
                  EventDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableEventData().getMutableMap().put(
                  eventData__.getKey(), eventData__.getValue());
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object eventId_ = "";
    /**
     * <pre>
     * Event ID
     * </pre>
     *
     * <code>string event_id = 1;</code>
     * @return The eventId.
     */
    public java.lang.String getEventId() {
      java.lang.Object ref = eventId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Event ID
     * </pre>
     *
     * <code>string event_id = 1;</code>
     * @return The bytes for eventId.
     */
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      java.lang.Object ref = eventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Event ID
     * </pre>
     *
     * <code>string event_id = 1;</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Event ID
     * </pre>
     *
     * <code>string event_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      eventId_ = getDefaultInstance().getEventId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Event ID
     * </pre>
     *
     * <code>string event_id = 1;</code>
     * @param value The bytes for eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     * User ID
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * User ID
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * User ID
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * User ID
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * User ID
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object notificationId_ = "";
    /**
     * <pre>
     * Notification ID
     * </pre>
     *
     * <code>string notification_id = 3;</code>
     * @return The notificationId.
     */
    public java.lang.String getNotificationId() {
      java.lang.Object ref = notificationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notificationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Notification ID
     * </pre>
     *
     * <code>string notification_id = 3;</code>
     * @return The bytes for notificationId.
     */
    public com.google.protobuf.ByteString
        getNotificationIdBytes() {
      java.lang.Object ref = notificationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notificationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Notification ID
     * </pre>
     *
     * <code>string notification_id = 3;</code>
     * @param value The notificationId to set.
     * @return This builder for chaining.
     */
    public Builder setNotificationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      notificationId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Notification ID
     * </pre>
     *
     * <code>string notification_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNotificationId() {
      notificationId_ = getDefaultInstance().getNotificationId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Notification ID
     * </pre>
     *
     * <code>string notification_id = 3;</code>
     * @param value The bytes for notificationId to set.
     * @return This builder for chaining.
     */
    public Builder setNotificationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      notificationId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object eventType_ = "";
    /**
     * <pre>
     * Event type
     * </pre>
     *
     * <code>string event_type = 4;</code>
     * @return The eventType.
     */
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Event type
     * </pre>
     *
     * <code>string event_type = 4;</code>
     * @return The bytes for eventType.
     */
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Event type
     * </pre>
     *
     * <code>string event_type = 4;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Event type
     * </pre>
     *
     * <code>string event_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      eventType_ = getDefaultInstance().getEventType();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Event type
     * </pre>
     *
     * <code>string event_type = 4;</code>
     * @param value The bytes for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.movieplatform.proto.common.DateTime eventTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> eventTimeBuilder_;
    /**
     * <pre>
     * When event occurred
     * </pre>
     *
     * <code>.proto.common.DateTime event_time = 5;</code>
     * @return Whether the eventTime field is set.
     */
    public boolean hasEventTime() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * When event occurred
     * </pre>
     *
     * <code>.proto.common.DateTime event_time = 5;</code>
     * @return The eventTime.
     */
    public com.movieplatform.proto.common.DateTime getEventTime() {
      if (eventTimeBuilder_ == null) {
        return eventTime_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : eventTime_;
      } else {
        return eventTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * When event occurred
     * </pre>
     *
     * <code>.proto.common.DateTime event_time = 5;</code>
     */
    public Builder setEventTime(com.movieplatform.proto.common.DateTime value) {
      if (eventTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventTime_ = value;
      } else {
        eventTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When event occurred
     * </pre>
     *
     * <code>.proto.common.DateTime event_time = 5;</code>
     */
    public Builder setEventTime(
        com.movieplatform.proto.common.DateTime.Builder builderForValue) {
      if (eventTimeBuilder_ == null) {
        eventTime_ = builderForValue.build();
      } else {
        eventTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When event occurred
     * </pre>
     *
     * <code>.proto.common.DateTime event_time = 5;</code>
     */
    public Builder mergeEventTime(com.movieplatform.proto.common.DateTime value) {
      if (eventTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          eventTime_ != null &&
          eventTime_ != com.movieplatform.proto.common.DateTime.getDefaultInstance()) {
          getEventTimeBuilder().mergeFrom(value);
        } else {
          eventTime_ = value;
        }
      } else {
        eventTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When event occurred
     * </pre>
     *
     * <code>.proto.common.DateTime event_time = 5;</code>
     */
    public Builder clearEventTime() {
      bitField0_ = (bitField0_ & ~0x00000010);
      eventTime_ = null;
      if (eventTimeBuilder_ != null) {
        eventTimeBuilder_.dispose();
        eventTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When event occurred
     * </pre>
     *
     * <code>.proto.common.DateTime event_time = 5;</code>
     */
    public com.movieplatform.proto.common.DateTime.Builder getEventTimeBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getEventTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * When event occurred
     * </pre>
     *
     * <code>.proto.common.DateTime event_time = 5;</code>
     */
    public com.movieplatform.proto.common.DateTimeOrBuilder getEventTimeOrBuilder() {
      if (eventTimeBuilder_ != null) {
        return eventTimeBuilder_.getMessageOrBuilder();
      } else {
        return eventTime_ == null ?
            com.movieplatform.proto.common.DateTime.getDefaultInstance() : eventTime_;
      }
    }
    /**
     * <pre>
     * When event occurred
     * </pre>
     *
     * <code>.proto.common.DateTime event_time = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> 
        getEventTimeFieldBuilder() {
      if (eventTimeBuilder_ == null) {
        eventTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder>(
                getEventTime(),
                getParentForChildren(),
                isClean());
        eventTime_ = null;
      }
      return eventTimeBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> eventData_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetEventData() {
      if (eventData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EventDataDefaultEntryHolder.defaultEntry);
      }
      return eventData_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableEventData() {
      if (eventData_ == null) {
        eventData_ = com.google.protobuf.MapField.newMapField(
            EventDataDefaultEntryHolder.defaultEntry);
      }
      if (!eventData_.isMutable()) {
        eventData_ = eventData_.copy();
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return eventData_;
    }
    public int getEventDataCount() {
      return internalGetEventData().getMap().size();
    }
    /**
     * <pre>
     * Event-specific data
     * </pre>
     *
     * <code>map&lt;string, string&gt; event_data = 6;</code>
     */
    @java.lang.Override
    public boolean containsEventData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetEventData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEventDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getEventData() {
      return getEventDataMap();
    }
    /**
     * <pre>
     * Event-specific data
     * </pre>
     *
     * <code>map&lt;string, string&gt; event_data = 6;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getEventDataMap() {
      return internalGetEventData().getMap();
    }
    /**
     * <pre>
     * Event-specific data
     * </pre>
     *
     * <code>map&lt;string, string&gt; event_data = 6;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getEventDataOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEventData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Event-specific data
     * </pre>
     *
     * <code>map&lt;string, string&gt; event_data = 6;</code>
     */
    @java.lang.Override
    public java.lang.String getEventDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEventData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearEventData() {
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableEventData().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Event-specific data
     * </pre>
     *
     * <code>map&lt;string, string&gt; event_data = 6;</code>
     */
    public Builder removeEventData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableEventData().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableEventData() {
      bitField0_ |= 0x00000020;
      return internalGetMutableEventData().getMutableMap();
    }
    /**
     * <pre>
     * Event-specific data
     * </pre>
     *
     * <code>map&lt;string, string&gt; event_data = 6;</code>
     */
    public Builder putEventData(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableEventData().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     * Event-specific data
     * </pre>
     *
     * <code>map&lt;string, string&gt; event_data = 6;</code>
     */
    public Builder putAllEventData(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableEventData().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000020;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.notification.EngagementEvent)
  }

  // @@protoc_insertion_point(class_scope:proto.notification.EngagementEvent)
  private static final com.movieplatform.proto.notification.EngagementEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.notification.EngagementEvent();
  }

  public static com.movieplatform.proto.notification.EngagementEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EngagementEvent>
      PARSER = new com.google.protobuf.AbstractParser<EngagementEvent>() {
    @java.lang.Override
    public EngagementEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EngagementEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EngagementEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.notification.EngagementEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

