// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playback/playback_req_res.proto

package com.movieplatform.proto.playback;

/**
 * <pre>
 * Get playback history response
 * </pre>
 *
 * Protobuf type {@code proto.playback.GetPlaybackHistoryResponse}
 */
public final class GetPlaybackHistoryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.playback.GetPlaybackHistoryResponse)
    GetPlaybackHistoryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetPlaybackHistoryResponse.newBuilder() to construct.
  private GetPlaybackHistoryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetPlaybackHistoryResponse() {
    sessions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetPlaybackHistoryResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_GetPlaybackHistoryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_GetPlaybackHistoryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.playback.GetPlaybackHistoryResponse.class, com.movieplatform.proto.playback.GetPlaybackHistoryResponse.Builder.class);
  }

  public static final int BASE_RESPONSE_FIELD_NUMBER = 1;
  private com.movieplatform.proto.common.BaseResponse baseResponse_;
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  @java.lang.Override
  public boolean hasBaseResponse() {
    return baseResponse_ != null;
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }

  public static final int SESSIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.movieplatform.proto.playback.PlaybackSession> sessions_;
  /**
   * <pre>
   * Playback sessions
   * </pre>
   *
   * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.movieplatform.proto.playback.PlaybackSession> getSessionsList() {
    return sessions_;
  }
  /**
   * <pre>
   * Playback sessions
   * </pre>
   *
   * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.movieplatform.proto.playback.PlaybackSessionOrBuilder> 
      getSessionsOrBuilderList() {
    return sessions_;
  }
  /**
   * <pre>
   * Playback sessions
   * </pre>
   *
   * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
   */
  @java.lang.Override
  public int getSessionsCount() {
    return sessions_.size();
  }
  /**
   * <pre>
   * Playback sessions
   * </pre>
   *
   * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.playback.PlaybackSession getSessions(int index) {
    return sessions_.get(index);
  }
  /**
   * <pre>
   * Playback sessions
   * </pre>
   *
   * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.playback.PlaybackSessionOrBuilder getSessionsOrBuilder(
      int index) {
    return sessions_.get(index);
  }

  public static final int PAGINATION_FIELD_NUMBER = 3;
  private com.movieplatform.proto.common.PaginationResponse pagination_;
  /**
   * <pre>
   * Pagination information
   * </pre>
   *
   * <code>.proto.common.PaginationResponse pagination = 3;</code>
   * @return Whether the pagination field is set.
   */
  @java.lang.Override
  public boolean hasPagination() {
    return pagination_ != null;
  }
  /**
   * <pre>
   * Pagination information
   * </pre>
   *
   * <code>.proto.common.PaginationResponse pagination = 3;</code>
   * @return The pagination.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.PaginationResponse getPagination() {
    return pagination_ == null ? com.movieplatform.proto.common.PaginationResponse.getDefaultInstance() : pagination_;
  }
  /**
   * <pre>
   * Pagination information
   * </pre>
   *
   * <code>.proto.common.PaginationResponse pagination = 3;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.PaginationResponseOrBuilder getPaginationOrBuilder() {
    return pagination_ == null ? com.movieplatform.proto.common.PaginationResponse.getDefaultInstance() : pagination_;
  }

  public static final int TOTAL_COUNT_FIELD_NUMBER = 4;
  private long totalCount_ = 0L;
  /**
   * <pre>
   * Total number of sessions
   * </pre>
   *
   * <code>int64 total_count = 4;</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public long getTotalCount() {
    return totalCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseResponse_ != null) {
      output.writeMessage(1, getBaseResponse());
    }
    for (int i = 0; i < sessions_.size(); i++) {
      output.writeMessage(2, sessions_.get(i));
    }
    if (pagination_ != null) {
      output.writeMessage(3, getPagination());
    }
    if (totalCount_ != 0L) {
      output.writeInt64(4, totalCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResponse());
    }
    for (int i = 0; i < sessions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, sessions_.get(i));
    }
    if (pagination_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPagination());
    }
    if (totalCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, totalCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.playback.GetPlaybackHistoryResponse)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.playback.GetPlaybackHistoryResponse other = (com.movieplatform.proto.playback.GetPlaybackHistoryResponse) obj;

    if (hasBaseResponse() != other.hasBaseResponse()) return false;
    if (hasBaseResponse()) {
      if (!getBaseResponse()
          .equals(other.getBaseResponse())) return false;
    }
    if (!getSessionsList()
        .equals(other.getSessionsList())) return false;
    if (hasPagination() != other.hasPagination()) return false;
    if (hasPagination()) {
      if (!getPagination()
          .equals(other.getPagination())) return false;
    }
    if (getTotalCount()
        != other.getTotalCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResponse()) {
      hash = (37 * hash) + BASE_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResponse().hashCode();
    }
    if (getSessionsCount() > 0) {
      hash = (37 * hash) + SESSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getSessionsList().hashCode();
    }
    if (hasPagination()) {
      hash = (37 * hash) + PAGINATION_FIELD_NUMBER;
      hash = (53 * hash) + getPagination().hashCode();
    }
    hash = (37 * hash) + TOTAL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalCount());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.playback.GetPlaybackHistoryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Get playback history response
   * </pre>
   *
   * Protobuf type {@code proto.playback.GetPlaybackHistoryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.playback.GetPlaybackHistoryResponse)
      com.movieplatform.proto.playback.GetPlaybackHistoryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_GetPlaybackHistoryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_GetPlaybackHistoryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.playback.GetPlaybackHistoryResponse.class, com.movieplatform.proto.playback.GetPlaybackHistoryResponse.Builder.class);
    }

    // Construct using com.movieplatform.proto.playback.GetPlaybackHistoryResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      if (sessionsBuilder_ == null) {
        sessions_ = java.util.Collections.emptyList();
      } else {
        sessions_ = null;
        sessionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      totalCount_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_GetPlaybackHistoryResponse_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.playback.GetPlaybackHistoryResponse getDefaultInstanceForType() {
      return com.movieplatform.proto.playback.GetPlaybackHistoryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.playback.GetPlaybackHistoryResponse build() {
      com.movieplatform.proto.playback.GetPlaybackHistoryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.playback.GetPlaybackHistoryResponse buildPartial() {
      com.movieplatform.proto.playback.GetPlaybackHistoryResponse result = new com.movieplatform.proto.playback.GetPlaybackHistoryResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.movieplatform.proto.playback.GetPlaybackHistoryResponse result) {
      if (sessionsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          sessions_ = java.util.Collections.unmodifiableList(sessions_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.sessions_ = sessions_;
      } else {
        result.sessions_ = sessionsBuilder_.build();
      }
    }

    private void buildPartial0(com.movieplatform.proto.playback.GetPlaybackHistoryResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseResponse_ = baseResponseBuilder_ == null
            ? baseResponse_
            : baseResponseBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pagination_ = paginationBuilder_ == null
            ? pagination_
            : paginationBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.totalCount_ = totalCount_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.playback.GetPlaybackHistoryResponse) {
        return mergeFrom((com.movieplatform.proto.playback.GetPlaybackHistoryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.playback.GetPlaybackHistoryResponse other) {
      if (other == com.movieplatform.proto.playback.GetPlaybackHistoryResponse.getDefaultInstance()) return this;
      if (other.hasBaseResponse()) {
        mergeBaseResponse(other.getBaseResponse());
      }
      if (sessionsBuilder_ == null) {
        if (!other.sessions_.isEmpty()) {
          if (sessions_.isEmpty()) {
            sessions_ = other.sessions_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSessionsIsMutable();
            sessions_.addAll(other.sessions_);
          }
          onChanged();
        }
      } else {
        if (!other.sessions_.isEmpty()) {
          if (sessionsBuilder_.isEmpty()) {
            sessionsBuilder_.dispose();
            sessionsBuilder_ = null;
            sessions_ = other.sessions_;
            bitField0_ = (bitField0_ & ~0x00000002);
            sessionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSessionsFieldBuilder() : null;
          } else {
            sessionsBuilder_.addAllMessages(other.sessions_);
          }
        }
      }
      if (other.hasPagination()) {
        mergePagination(other.getPagination());
      }
      if (other.getTotalCount() != 0L) {
        setTotalCount(other.getTotalCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBaseResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.movieplatform.proto.playback.PlaybackSession m =
                  input.readMessage(
                      com.movieplatform.proto.playback.PlaybackSession.parser(),
                      extensionRegistry);
              if (sessionsBuilder_ == null) {
                ensureSessionsIsMutable();
                sessions_.add(m);
              } else {
                sessionsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getPaginationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              totalCount_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.movieplatform.proto.common.BaseResponse baseResponse_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> baseResponseBuilder_;
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return Whether the baseResponse field is set.
     */
    public boolean hasBaseResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return The baseResponse.
     */
    public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
      if (baseResponseBuilder_ == null) {
        return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      } else {
        return baseResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResponse_ = value;
      } else {
        baseResponseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(
        com.movieplatform.proto.common.BaseResponse.Builder builderForValue) {
      if (baseResponseBuilder_ == null) {
        baseResponse_ = builderForValue.build();
      } else {
        baseResponseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder mergeBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseResponse_ != null &&
          baseResponse_ != com.movieplatform.proto.common.BaseResponse.getDefaultInstance()) {
          getBaseResponseBuilder().mergeFrom(value);
        } else {
          baseResponse_ = value;
        }
      } else {
        baseResponseBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder clearBaseResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponse.Builder getBaseResponseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBaseResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
      if (baseResponseBuilder_ != null) {
        return baseResponseBuilder_.getMessageOrBuilder();
      } else {
        return baseResponse_ == null ?
            com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> 
        getBaseResponseFieldBuilder() {
      if (baseResponseBuilder_ == null) {
        baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder>(
                getBaseResponse(),
                getParentForChildren(),
                isClean());
        baseResponse_ = null;
      }
      return baseResponseBuilder_;
    }

    private java.util.List<com.movieplatform.proto.playback.PlaybackSession> sessions_ =
      java.util.Collections.emptyList();
    private void ensureSessionsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        sessions_ = new java.util.ArrayList<com.movieplatform.proto.playback.PlaybackSession>(sessions_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.movieplatform.proto.playback.PlaybackSession, com.movieplatform.proto.playback.PlaybackSession.Builder, com.movieplatform.proto.playback.PlaybackSessionOrBuilder> sessionsBuilder_;

    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public java.util.List<com.movieplatform.proto.playback.PlaybackSession> getSessionsList() {
      if (sessionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sessions_);
      } else {
        return sessionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public int getSessionsCount() {
      if (sessionsBuilder_ == null) {
        return sessions_.size();
      } else {
        return sessionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public com.movieplatform.proto.playback.PlaybackSession getSessions(int index) {
      if (sessionsBuilder_ == null) {
        return sessions_.get(index);
      } else {
        return sessionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public Builder setSessions(
        int index, com.movieplatform.proto.playback.PlaybackSession value) {
      if (sessionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSessionsIsMutable();
        sessions_.set(index, value);
        onChanged();
      } else {
        sessionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public Builder setSessions(
        int index, com.movieplatform.proto.playback.PlaybackSession.Builder builderForValue) {
      if (sessionsBuilder_ == null) {
        ensureSessionsIsMutable();
        sessions_.set(index, builderForValue.build());
        onChanged();
      } else {
        sessionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public Builder addSessions(com.movieplatform.proto.playback.PlaybackSession value) {
      if (sessionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSessionsIsMutable();
        sessions_.add(value);
        onChanged();
      } else {
        sessionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public Builder addSessions(
        int index, com.movieplatform.proto.playback.PlaybackSession value) {
      if (sessionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSessionsIsMutable();
        sessions_.add(index, value);
        onChanged();
      } else {
        sessionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public Builder addSessions(
        com.movieplatform.proto.playback.PlaybackSession.Builder builderForValue) {
      if (sessionsBuilder_ == null) {
        ensureSessionsIsMutable();
        sessions_.add(builderForValue.build());
        onChanged();
      } else {
        sessionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public Builder addSessions(
        int index, com.movieplatform.proto.playback.PlaybackSession.Builder builderForValue) {
      if (sessionsBuilder_ == null) {
        ensureSessionsIsMutable();
        sessions_.add(index, builderForValue.build());
        onChanged();
      } else {
        sessionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public Builder addAllSessions(
        java.lang.Iterable<? extends com.movieplatform.proto.playback.PlaybackSession> values) {
      if (sessionsBuilder_ == null) {
        ensureSessionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sessions_);
        onChanged();
      } else {
        sessionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public Builder clearSessions() {
      if (sessionsBuilder_ == null) {
        sessions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        sessionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public Builder removeSessions(int index) {
      if (sessionsBuilder_ == null) {
        ensureSessionsIsMutable();
        sessions_.remove(index);
        onChanged();
      } else {
        sessionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public com.movieplatform.proto.playback.PlaybackSession.Builder getSessionsBuilder(
        int index) {
      return getSessionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public com.movieplatform.proto.playback.PlaybackSessionOrBuilder getSessionsOrBuilder(
        int index) {
      if (sessionsBuilder_ == null) {
        return sessions_.get(index);  } else {
        return sessionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public java.util.List<? extends com.movieplatform.proto.playback.PlaybackSessionOrBuilder> 
         getSessionsOrBuilderList() {
      if (sessionsBuilder_ != null) {
        return sessionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sessions_);
      }
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public com.movieplatform.proto.playback.PlaybackSession.Builder addSessionsBuilder() {
      return getSessionsFieldBuilder().addBuilder(
          com.movieplatform.proto.playback.PlaybackSession.getDefaultInstance());
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public com.movieplatform.proto.playback.PlaybackSession.Builder addSessionsBuilder(
        int index) {
      return getSessionsFieldBuilder().addBuilder(
          index, com.movieplatform.proto.playback.PlaybackSession.getDefaultInstance());
    }
    /**
     * <pre>
     * Playback sessions
     * </pre>
     *
     * <code>repeated .proto.playback.PlaybackSession sessions = 2;</code>
     */
    public java.util.List<com.movieplatform.proto.playback.PlaybackSession.Builder> 
         getSessionsBuilderList() {
      return getSessionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.movieplatform.proto.playback.PlaybackSession, com.movieplatform.proto.playback.PlaybackSession.Builder, com.movieplatform.proto.playback.PlaybackSessionOrBuilder> 
        getSessionsFieldBuilder() {
      if (sessionsBuilder_ == null) {
        sessionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.movieplatform.proto.playback.PlaybackSession, com.movieplatform.proto.playback.PlaybackSession.Builder, com.movieplatform.proto.playback.PlaybackSessionOrBuilder>(
                sessions_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        sessions_ = null;
      }
      return sessionsBuilder_;
    }

    private com.movieplatform.proto.common.PaginationResponse pagination_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.PaginationResponse, com.movieplatform.proto.common.PaginationResponse.Builder, com.movieplatform.proto.common.PaginationResponseOrBuilder> paginationBuilder_;
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     * @return Whether the pagination field is set.
     */
    public boolean hasPagination() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     * @return The pagination.
     */
    public com.movieplatform.proto.common.PaginationResponse getPagination() {
      if (paginationBuilder_ == null) {
        return pagination_ == null ? com.movieplatform.proto.common.PaginationResponse.getDefaultInstance() : pagination_;
      } else {
        return paginationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    public Builder setPagination(com.movieplatform.proto.common.PaginationResponse value) {
      if (paginationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pagination_ = value;
      } else {
        paginationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    public Builder setPagination(
        com.movieplatform.proto.common.PaginationResponse.Builder builderForValue) {
      if (paginationBuilder_ == null) {
        pagination_ = builderForValue.build();
      } else {
        paginationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    public Builder mergePagination(com.movieplatform.proto.common.PaginationResponse value) {
      if (paginationBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          pagination_ != null &&
          pagination_ != com.movieplatform.proto.common.PaginationResponse.getDefaultInstance()) {
          getPaginationBuilder().mergeFrom(value);
        } else {
          pagination_ = value;
        }
      } else {
        paginationBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    public Builder clearPagination() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    public com.movieplatform.proto.common.PaginationResponse.Builder getPaginationBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getPaginationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    public com.movieplatform.proto.common.PaginationResponseOrBuilder getPaginationOrBuilder() {
      if (paginationBuilder_ != null) {
        return paginationBuilder_.getMessageOrBuilder();
      } else {
        return pagination_ == null ?
            com.movieplatform.proto.common.PaginationResponse.getDefaultInstance() : pagination_;
      }
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.PaginationResponse, com.movieplatform.proto.common.PaginationResponse.Builder, com.movieplatform.proto.common.PaginationResponseOrBuilder> 
        getPaginationFieldBuilder() {
      if (paginationBuilder_ == null) {
        paginationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.movieplatform.proto.common.PaginationResponse, com.movieplatform.proto.common.PaginationResponse.Builder, com.movieplatform.proto.common.PaginationResponseOrBuilder>(
                getPagination(),
                getParentForChildren(),
                isClean());
        pagination_ = null;
      }
      return paginationBuilder_;
    }

    private long totalCount_ ;
    /**
     * <pre>
     * Total number of sessions
     * </pre>
     *
     * <code>int64 total_count = 4;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public long getTotalCount() {
      return totalCount_;
    }
    /**
     * <pre>
     * Total number of sessions
     * </pre>
     *
     * <code>int64 total_count = 4;</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(long value) {
      
      totalCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total number of sessions
     * </pre>
     *
     * <code>int64 total_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      totalCount_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.playback.GetPlaybackHistoryResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.playback.GetPlaybackHistoryResponse)
  private static final com.movieplatform.proto.playback.GetPlaybackHistoryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.playback.GetPlaybackHistoryResponse();
  }

  public static com.movieplatform.proto.playback.GetPlaybackHistoryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPlaybackHistoryResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetPlaybackHistoryResponse>() {
    @java.lang.Override
    public GetPlaybackHistoryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetPlaybackHistoryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPlaybackHistoryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.playback.GetPlaybackHistoryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

