// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/auth_req_res.proto

package com.movieplatform.proto.auth;

/**
 * <pre>
 * Resend verification response
 * </pre>
 *
 * Protobuf type {@code proto.auth.ResendVerificationResponse}
 */
public final class ResendVerificationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.auth.ResendVerificationResponse)
    ResendVerificationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResendVerificationResponse.newBuilder() to construct.
  private ResendVerificationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResendVerificationResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResendVerificationResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.auth.AuthReqResProto.internal_static_proto_auth_ResendVerificationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.auth.AuthReqResProto.internal_static_proto_auth_ResendVerificationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.auth.ResendVerificationResponse.class, com.movieplatform.proto.auth.ResendVerificationResponse.Builder.class);
  }

  public static final int BASE_RESPONSE_FIELD_NUMBER = 1;
  private com.movieplatform.proto.common.BaseResponse baseResponse_;
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  @java.lang.Override
  public boolean hasBaseResponse() {
    return baseResponse_ != null;
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }

  public static final int VERIFICATION_SENT_FIELD_NUMBER = 2;
  private boolean verificationSent_ = false;
  /**
   * <pre>
   * Whether verification was sent
   * </pre>
   *
   * <code>bool verification_sent = 2;</code>
   * @return The verificationSent.
   */
  @java.lang.Override
  public boolean getVerificationSent() {
    return verificationSent_;
  }

  public static final int SENT_AT_FIELD_NUMBER = 3;
  private com.movieplatform.proto.common.DateTime sentAt_;
  /**
   * <pre>
   * When verification was sent
   * </pre>
   *
   * <code>.proto.common.DateTime sent_at = 3;</code>
   * @return Whether the sentAt field is set.
   */
  @java.lang.Override
  public boolean hasSentAt() {
    return sentAt_ != null;
  }
  /**
   * <pre>
   * When verification was sent
   * </pre>
   *
   * <code>.proto.common.DateTime sent_at = 3;</code>
   * @return The sentAt.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTime getSentAt() {
    return sentAt_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : sentAt_;
  }
  /**
   * <pre>
   * When verification was sent
   * </pre>
   *
   * <code>.proto.common.DateTime sent_at = 3;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTimeOrBuilder getSentAtOrBuilder() {
    return sentAt_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : sentAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseResponse_ != null) {
      output.writeMessage(1, getBaseResponse());
    }
    if (verificationSent_ != false) {
      output.writeBool(2, verificationSent_);
    }
    if (sentAt_ != null) {
      output.writeMessage(3, getSentAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResponse());
    }
    if (verificationSent_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, verificationSent_);
    }
    if (sentAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSentAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.auth.ResendVerificationResponse)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.auth.ResendVerificationResponse other = (com.movieplatform.proto.auth.ResendVerificationResponse) obj;

    if (hasBaseResponse() != other.hasBaseResponse()) return false;
    if (hasBaseResponse()) {
      if (!getBaseResponse()
          .equals(other.getBaseResponse())) return false;
    }
    if (getVerificationSent()
        != other.getVerificationSent()) return false;
    if (hasSentAt() != other.hasSentAt()) return false;
    if (hasSentAt()) {
      if (!getSentAt()
          .equals(other.getSentAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResponse()) {
      hash = (37 * hash) + BASE_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResponse().hashCode();
    }
    hash = (37 * hash) + VERIFICATION_SENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getVerificationSent());
    if (hasSentAt()) {
      hash = (37 * hash) + SENT_AT_FIELD_NUMBER;
      hash = (53 * hash) + getSentAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.auth.ResendVerificationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.auth.ResendVerificationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.auth.ResendVerificationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.auth.ResendVerificationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.auth.ResendVerificationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.auth.ResendVerificationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.auth.ResendVerificationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.auth.ResendVerificationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.auth.ResendVerificationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.auth.ResendVerificationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.auth.ResendVerificationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.auth.ResendVerificationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.auth.ResendVerificationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Resend verification response
   * </pre>
   *
   * Protobuf type {@code proto.auth.ResendVerificationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.auth.ResendVerificationResponse)
      com.movieplatform.proto.auth.ResendVerificationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.auth.AuthReqResProto.internal_static_proto_auth_ResendVerificationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.auth.AuthReqResProto.internal_static_proto_auth_ResendVerificationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.auth.ResendVerificationResponse.class, com.movieplatform.proto.auth.ResendVerificationResponse.Builder.class);
    }

    // Construct using com.movieplatform.proto.auth.ResendVerificationResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      verificationSent_ = false;
      sentAt_ = null;
      if (sentAtBuilder_ != null) {
        sentAtBuilder_.dispose();
        sentAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.auth.AuthReqResProto.internal_static_proto_auth_ResendVerificationResponse_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.auth.ResendVerificationResponse getDefaultInstanceForType() {
      return com.movieplatform.proto.auth.ResendVerificationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.auth.ResendVerificationResponse build() {
      com.movieplatform.proto.auth.ResendVerificationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.auth.ResendVerificationResponse buildPartial() {
      com.movieplatform.proto.auth.ResendVerificationResponse result = new com.movieplatform.proto.auth.ResendVerificationResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.movieplatform.proto.auth.ResendVerificationResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseResponse_ = baseResponseBuilder_ == null
            ? baseResponse_
            : baseResponseBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.verificationSent_ = verificationSent_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sentAt_ = sentAtBuilder_ == null
            ? sentAt_
            : sentAtBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.auth.ResendVerificationResponse) {
        return mergeFrom((com.movieplatform.proto.auth.ResendVerificationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.auth.ResendVerificationResponse other) {
      if (other == com.movieplatform.proto.auth.ResendVerificationResponse.getDefaultInstance()) return this;
      if (other.hasBaseResponse()) {
        mergeBaseResponse(other.getBaseResponse());
      }
      if (other.getVerificationSent() != false) {
        setVerificationSent(other.getVerificationSent());
      }
      if (other.hasSentAt()) {
        mergeSentAt(other.getSentAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBaseResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              verificationSent_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getSentAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.movieplatform.proto.common.BaseResponse baseResponse_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> baseResponseBuilder_;
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return Whether the baseResponse field is set.
     */
    public boolean hasBaseResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return The baseResponse.
     */
    public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
      if (baseResponseBuilder_ == null) {
        return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      } else {
        return baseResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResponse_ = value;
      } else {
        baseResponseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(
        com.movieplatform.proto.common.BaseResponse.Builder builderForValue) {
      if (baseResponseBuilder_ == null) {
        baseResponse_ = builderForValue.build();
      } else {
        baseResponseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder mergeBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseResponse_ != null &&
          baseResponse_ != com.movieplatform.proto.common.BaseResponse.getDefaultInstance()) {
          getBaseResponseBuilder().mergeFrom(value);
        } else {
          baseResponse_ = value;
        }
      } else {
        baseResponseBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder clearBaseResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponse.Builder getBaseResponseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBaseResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
      if (baseResponseBuilder_ != null) {
        return baseResponseBuilder_.getMessageOrBuilder();
      } else {
        return baseResponse_ == null ?
            com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> 
        getBaseResponseFieldBuilder() {
      if (baseResponseBuilder_ == null) {
        baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder>(
                getBaseResponse(),
                getParentForChildren(),
                isClean());
        baseResponse_ = null;
      }
      return baseResponseBuilder_;
    }

    private boolean verificationSent_ ;
    /**
     * <pre>
     * Whether verification was sent
     * </pre>
     *
     * <code>bool verification_sent = 2;</code>
     * @return The verificationSent.
     */
    @java.lang.Override
    public boolean getVerificationSent() {
      return verificationSent_;
    }
    /**
     * <pre>
     * Whether verification was sent
     * </pre>
     *
     * <code>bool verification_sent = 2;</code>
     * @param value The verificationSent to set.
     * @return This builder for chaining.
     */
    public Builder setVerificationSent(boolean value) {
      
      verificationSent_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether verification was sent
     * </pre>
     *
     * <code>bool verification_sent = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVerificationSent() {
      bitField0_ = (bitField0_ & ~0x00000002);
      verificationSent_ = false;
      onChanged();
      return this;
    }

    private com.movieplatform.proto.common.DateTime sentAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> sentAtBuilder_;
    /**
     * <pre>
     * When verification was sent
     * </pre>
     *
     * <code>.proto.common.DateTime sent_at = 3;</code>
     * @return Whether the sentAt field is set.
     */
    public boolean hasSentAt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * When verification was sent
     * </pre>
     *
     * <code>.proto.common.DateTime sent_at = 3;</code>
     * @return The sentAt.
     */
    public com.movieplatform.proto.common.DateTime getSentAt() {
      if (sentAtBuilder_ == null) {
        return sentAt_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : sentAt_;
      } else {
        return sentAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * When verification was sent
     * </pre>
     *
     * <code>.proto.common.DateTime sent_at = 3;</code>
     */
    public Builder setSentAt(com.movieplatform.proto.common.DateTime value) {
      if (sentAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sentAt_ = value;
      } else {
        sentAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When verification was sent
     * </pre>
     *
     * <code>.proto.common.DateTime sent_at = 3;</code>
     */
    public Builder setSentAt(
        com.movieplatform.proto.common.DateTime.Builder builderForValue) {
      if (sentAtBuilder_ == null) {
        sentAt_ = builderForValue.build();
      } else {
        sentAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When verification was sent
     * </pre>
     *
     * <code>.proto.common.DateTime sent_at = 3;</code>
     */
    public Builder mergeSentAt(com.movieplatform.proto.common.DateTime value) {
      if (sentAtBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          sentAt_ != null &&
          sentAt_ != com.movieplatform.proto.common.DateTime.getDefaultInstance()) {
          getSentAtBuilder().mergeFrom(value);
        } else {
          sentAt_ = value;
        }
      } else {
        sentAtBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When verification was sent
     * </pre>
     *
     * <code>.proto.common.DateTime sent_at = 3;</code>
     */
    public Builder clearSentAt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      sentAt_ = null;
      if (sentAtBuilder_ != null) {
        sentAtBuilder_.dispose();
        sentAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When verification was sent
     * </pre>
     *
     * <code>.proto.common.DateTime sent_at = 3;</code>
     */
    public com.movieplatform.proto.common.DateTime.Builder getSentAtBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getSentAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * When verification was sent
     * </pre>
     *
     * <code>.proto.common.DateTime sent_at = 3;</code>
     */
    public com.movieplatform.proto.common.DateTimeOrBuilder getSentAtOrBuilder() {
      if (sentAtBuilder_ != null) {
        return sentAtBuilder_.getMessageOrBuilder();
      } else {
        return sentAt_ == null ?
            com.movieplatform.proto.common.DateTime.getDefaultInstance() : sentAt_;
      }
    }
    /**
     * <pre>
     * When verification was sent
     * </pre>
     *
     * <code>.proto.common.DateTime sent_at = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> 
        getSentAtFieldBuilder() {
      if (sentAtBuilder_ == null) {
        sentAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder>(
                getSentAt(),
                getParentForChildren(),
                isClean());
        sentAt_ = null;
      }
      return sentAtBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.auth.ResendVerificationResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.auth.ResendVerificationResponse)
  private static final com.movieplatform.proto.auth.ResendVerificationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.auth.ResendVerificationResponse();
  }

  public static com.movieplatform.proto.auth.ResendVerificationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResendVerificationResponse>
      PARSER = new com.google.protobuf.AbstractParser<ResendVerificationResponse>() {
    @java.lang.Override
    public ResendVerificationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResendVerificationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResendVerificationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.auth.ResendVerificationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

