// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/common_types.proto

package com.movieplatform.proto.common;

/**
 * <pre>
 * Currency and monetary amounts
 * </pre>
 *
 * Protobuf type {@code proto.common.Money}
 */
public final class Money extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.common.Money)
    MoneyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Money.newBuilder() to construct.
  private Money(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Money() {
    currencyCode_ = "";
    formattedAmount_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Money();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.common.CommonTypesProto.internal_static_proto_common_Money_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.common.CommonTypesProto.internal_static_proto_common_Money_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.common.Money.class, com.movieplatform.proto.common.Money.Builder.class);
  }

  public static final int CURRENCY_CODE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object currencyCode_ = "";
  /**
   * <pre>
   * ISO currency code (e.g., USD, EUR)
   * </pre>
   *
   * <code>string currency_code = 1;</code>
   * @return The currencyCode.
   */
  @java.lang.Override
  public java.lang.String getCurrencyCode() {
    java.lang.Object ref = currencyCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currencyCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ISO currency code (e.g., USD, EUR)
   * </pre>
   *
   * <code>string currency_code = 1;</code>
   * @return The bytes for currencyCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrencyCodeBytes() {
    java.lang.Object ref = currencyCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currencyCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_CENTS_FIELD_NUMBER = 2;
  private long amountCents_ = 0L;
  /**
   * <pre>
   * Amount in smallest currency unit (cents)
   * </pre>
   *
   * <code>int64 amount_cents = 2;</code>
   * @return The amountCents.
   */
  @java.lang.Override
  public long getAmountCents() {
    return amountCents_;
  }

  public static final int FORMATTED_AMOUNT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object formattedAmount_ = "";
  /**
   * <pre>
   * Human-readable formatted amount
   * </pre>
   *
   * <code>string formatted_amount = 3;</code>
   * @return The formattedAmount.
   */
  @java.lang.Override
  public java.lang.String getFormattedAmount() {
    java.lang.Object ref = formattedAmount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      formattedAmount_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Human-readable formatted amount
   * </pre>
   *
   * <code>string formatted_amount = 3;</code>
   * @return The bytes for formattedAmount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFormattedAmountBytes() {
    java.lang.Object ref = formattedAmount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      formattedAmount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currencyCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currencyCode_);
    }
    if (amountCents_ != 0L) {
      output.writeInt64(2, amountCents_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(formattedAmount_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, formattedAmount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currencyCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currencyCode_);
    }
    if (amountCents_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, amountCents_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(formattedAmount_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, formattedAmount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.common.Money)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.common.Money other = (com.movieplatform.proto.common.Money) obj;

    if (!getCurrencyCode()
        .equals(other.getCurrencyCode())) return false;
    if (getAmountCents()
        != other.getAmountCents()) return false;
    if (!getFormattedAmount()
        .equals(other.getFormattedAmount())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENCY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrencyCode().hashCode();
    hash = (37 * hash) + AMOUNT_CENTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmountCents());
    hash = (37 * hash) + FORMATTED_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getFormattedAmount().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.common.Money parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.common.Money parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.common.Money parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.common.Money parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.common.Money parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.common.Money parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.common.Money parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.common.Money parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.common.Money parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.common.Money parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.common.Money parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.common.Money parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.common.Money prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Currency and monetary amounts
   * </pre>
   *
   * Protobuf type {@code proto.common.Money}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.common.Money)
      com.movieplatform.proto.common.MoneyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.common.CommonTypesProto.internal_static_proto_common_Money_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.common.CommonTypesProto.internal_static_proto_common_Money_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.common.Money.class, com.movieplatform.proto.common.Money.Builder.class);
    }

    // Construct using com.movieplatform.proto.common.Money.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      currencyCode_ = "";
      amountCents_ = 0L;
      formattedAmount_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.common.CommonTypesProto.internal_static_proto_common_Money_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.common.Money getDefaultInstanceForType() {
      return com.movieplatform.proto.common.Money.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.common.Money build() {
      com.movieplatform.proto.common.Money result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.common.Money buildPartial() {
      com.movieplatform.proto.common.Money result = new com.movieplatform.proto.common.Money(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.movieplatform.proto.common.Money result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.currencyCode_ = currencyCode_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.amountCents_ = amountCents_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.formattedAmount_ = formattedAmount_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.common.Money) {
        return mergeFrom((com.movieplatform.proto.common.Money)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.common.Money other) {
      if (other == com.movieplatform.proto.common.Money.getDefaultInstance()) return this;
      if (!other.getCurrencyCode().isEmpty()) {
        currencyCode_ = other.currencyCode_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAmountCents() != 0L) {
        setAmountCents(other.getAmountCents());
      }
      if (!other.getFormattedAmount().isEmpty()) {
        formattedAmount_ = other.formattedAmount_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              currencyCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              amountCents_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              formattedAmount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object currencyCode_ = "";
    /**
     * <pre>
     * ISO currency code (e.g., USD, EUR)
     * </pre>
     *
     * <code>string currency_code = 1;</code>
     * @return The currencyCode.
     */
    public java.lang.String getCurrencyCode() {
      java.lang.Object ref = currencyCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ISO currency code (e.g., USD, EUR)
     * </pre>
     *
     * <code>string currency_code = 1;</code>
     * @return The bytes for currencyCode.
     */
    public com.google.protobuf.ByteString
        getCurrencyCodeBytes() {
      java.lang.Object ref = currencyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ISO currency code (e.g., USD, EUR)
     * </pre>
     *
     * <code>string currency_code = 1;</code>
     * @param value The currencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      currencyCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISO currency code (e.g., USD, EUR)
     * </pre>
     *
     * <code>string currency_code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrencyCode() {
      currencyCode_ = getDefaultInstance().getCurrencyCode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISO currency code (e.g., USD, EUR)
     * </pre>
     *
     * <code>string currency_code = 1;</code>
     * @param value The bytes for currencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      currencyCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long amountCents_ ;
    /**
     * <pre>
     * Amount in smallest currency unit (cents)
     * </pre>
     *
     * <code>int64 amount_cents = 2;</code>
     * @return The amountCents.
     */
    @java.lang.Override
    public long getAmountCents() {
      return amountCents_;
    }
    /**
     * <pre>
     * Amount in smallest currency unit (cents)
     * </pre>
     *
     * <code>int64 amount_cents = 2;</code>
     * @param value The amountCents to set.
     * @return This builder for chaining.
     */
    public Builder setAmountCents(long value) {
      
      amountCents_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Amount in smallest currency unit (cents)
     * </pre>
     *
     * <code>int64 amount_cents = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmountCents() {
      bitField0_ = (bitField0_ & ~0x00000002);
      amountCents_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object formattedAmount_ = "";
    /**
     * <pre>
     * Human-readable formatted amount
     * </pre>
     *
     * <code>string formatted_amount = 3;</code>
     * @return The formattedAmount.
     */
    public java.lang.String getFormattedAmount() {
      java.lang.Object ref = formattedAmount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        formattedAmount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Human-readable formatted amount
     * </pre>
     *
     * <code>string formatted_amount = 3;</code>
     * @return The bytes for formattedAmount.
     */
    public com.google.protobuf.ByteString
        getFormattedAmountBytes() {
      java.lang.Object ref = formattedAmount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        formattedAmount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Human-readable formatted amount
     * </pre>
     *
     * <code>string formatted_amount = 3;</code>
     * @param value The formattedAmount to set.
     * @return This builder for chaining.
     */
    public Builder setFormattedAmount(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      formattedAmount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Human-readable formatted amount
     * </pre>
     *
     * <code>string formatted_amount = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFormattedAmount() {
      formattedAmount_ = getDefaultInstance().getFormattedAmount();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Human-readable formatted amount
     * </pre>
     *
     * <code>string formatted_amount = 3;</code>
     * @param value The bytes for formattedAmount to set.
     * @return This builder for chaining.
     */
    public Builder setFormattedAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      formattedAmount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.common.Money)
  }

  // @@protoc_insertion_point(class_scope:proto.common.Money)
  private static final com.movieplatform.proto.common.Money DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.common.Money();
  }

  public static com.movieplatform.proto.common.Money getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Money>
      PARSER = new com.google.protobuf.AbstractParser<Money>() {
    @java.lang.Override
    public Money parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Money> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Money> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.common.Money getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

