// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/base_request.proto

package com.movieplatform.proto.common;

public interface RequestMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.common.RequestMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Client user agent
   * </pre>
   *
   * <code>string user_agent = 1;</code>
   * @return The userAgent.
   */
  java.lang.String getUserAgent();
  /**
   * <pre>
   * Client user agent
   * </pre>
   *
   * <code>string user_agent = 1;</code>
   * @return The bytes for userAgent.
   */
  com.google.protobuf.ByteString
      getUserAgentBytes();

  /**
   * <pre>
   * Client IP address
   * </pre>
   *
   * <code>string ip_address = 2;</code>
   * @return The ipAddress.
   */
  java.lang.String getIpAddress();
  /**
   * <pre>
   * Client IP address
   * </pre>
   *
   * <code>string ip_address = 2;</code>
   * @return The bytes for ipAddress.
   */
  com.google.protobuf.ByteString
      getIpAddressBytes();

  /**
   * <pre>
   * User session identifier
   * </pre>
   *
   * <code>string session_id = 3;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * User session identifier
   * </pre>
   *
   * <code>string session_id = 3;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * Correlation ID for distributed tracing
   * </pre>
   *
   * <code>string correlation_id = 4;</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <pre>
   * Correlation ID for distributed tracing
   * </pre>
   *
   * <code>string correlation_id = 4;</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  /**
   * <pre>
   * Custom request headers
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 5;</code>
   */
  int getCustomHeadersCount();
  /**
   * <pre>
   * Custom request headers
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 5;</code>
   */
  boolean containsCustomHeaders(
      java.lang.String key);
  /**
   * Use {@link #getCustomHeadersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getCustomHeaders();
  /**
   * <pre>
   * Custom request headers
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getCustomHeadersMap();
  /**
   * <pre>
   * Custom request headers
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 5;</code>
   */
  /* nullable */
java.lang.String getCustomHeadersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * Custom request headers
   * </pre>
   *
   * <code>map&lt;string, string&gt; custom_headers = 5;</code>
   */
  java.lang.String getCustomHeadersOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * User locale preference
   * </pre>
   *
   * <code>string locale = 6;</code>
   * @return The locale.
   */
  java.lang.String getLocale();
  /**
   * <pre>
   * User locale preference
   * </pre>
   *
   * <code>string locale = 6;</code>
   * @return The bytes for locale.
   */
  com.google.protobuf.ByteString
      getLocaleBytes();

  /**
   * <pre>
   * User timezone
   * </pre>
   *
   * <code>string timezone = 7;</code>
   * @return The timezone.
   */
  java.lang.String getTimezone();
  /**
   * <pre>
   * User timezone
   * </pre>
   *
   * <code>string timezone = 7;</code>
   * @return The bytes for timezone.
   */
  com.google.protobuf.ByteString
      getTimezoneBytes();
}
