// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation/recommendation_req_res.proto

package com.movieplatform.proto.recommendation;

public interface AnalyticsMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.recommendation.AnalyticsMetric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Metric name
   * </pre>
   *
   * <code>string metric_name = 1;</code>
   * @return The metricName.
   */
  java.lang.String getMetricName();
  /**
   * <pre>
   * Metric name
   * </pre>
   *
   * <code>string metric_name = 1;</code>
   * @return The bytes for metricName.
   */
  com.google.protobuf.ByteString
      getMetricNameBytes();

  /**
   * <pre>
   * Metric value
   * </pre>
   *
   * <code>float metric_value = 2;</code>
   * @return The metricValue.
   */
  float getMetricValue();

  /**
   * <pre>
   * Metric unit
   * </pre>
   *
   * <code>string metric_unit = 3;</code>
   * @return The metricUnit.
   */
  java.lang.String getMetricUnit();
  /**
   * <pre>
   * Metric unit
   * </pre>
   *
   * <code>string metric_unit = 3;</code>
   * @return The bytes for metricUnit.
   */
  com.google.protobuf.ByteString
      getMetricUnitBytes();

  /**
   * <pre>
   * Date of metric
   * </pre>
   *
   * <code>.proto.common.DateTime metric_date = 4;</code>
   * @return Whether the metricDate field is set.
   */
  boolean hasMetricDate();
  /**
   * <pre>
   * Date of metric
   * </pre>
   *
   * <code>.proto.common.DateTime metric_date = 4;</code>
   * @return The metricDate.
   */
  com.movieplatform.proto.common.DateTime getMetricDate();
  /**
   * <pre>
   * Date of metric
   * </pre>
   *
   * <code>.proto.common.DateTime metric_date = 4;</code>
   */
  com.movieplatform.proto.common.DateTimeOrBuilder getMetricDateOrBuilder();

  /**
   * <pre>
   * Aggregation level
   * </pre>
   *
   * <code>string aggregation_level = 5;</code>
   * @return The aggregationLevel.
   */
  java.lang.String getAggregationLevel();
  /**
   * <pre>
   * Aggregation level
   * </pre>
   *
   * <code>string aggregation_level = 5;</code>
   * @return The bytes for aggregationLevel.
   */
  com.google.protobuf.ByteString
      getAggregationLevelBytes();

  /**
   * <pre>
   * Metric dimensions
   * </pre>
   *
   * <code>map&lt;string, string&gt; dimensions = 6;</code>
   */
  int getDimensionsCount();
  /**
   * <pre>
   * Metric dimensions
   * </pre>
   *
   * <code>map&lt;string, string&gt; dimensions = 6;</code>
   */
  boolean containsDimensions(
      java.lang.String key);
  /**
   * Use {@link #getDimensionsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getDimensions();
  /**
   * <pre>
   * Metric dimensions
   * </pre>
   *
   * <code>map&lt;string, string&gt; dimensions = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getDimensionsMap();
  /**
   * <pre>
   * Metric dimensions
   * </pre>
   *
   * <code>map&lt;string, string&gt; dimensions = 6;</code>
   */
  /* nullable */
java.lang.String getDimensionsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * Metric dimensions
   * </pre>
   *
   * <code>map&lt;string, string&gt; dimensions = 6;</code>
   */
  java.lang.String getDimensionsOrThrow(
      java.lang.String key);
}
