// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation/recommendation_req_res.proto

package com.movieplatform.proto.recommendation;

/**
 * <pre>
 * Personalized recommendations response
 * </pre>
 *
 * Protobuf type {@code proto.recommendation.GetPersonalizedRecommendationsResponse}
 */
public final class GetPersonalizedRecommendationsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.recommendation.GetPersonalizedRecommendationsResponse)
    GetPersonalizedRecommendationsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetPersonalizedRecommendationsResponse.newBuilder() to construct.
  private GetPersonalizedRecommendationsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetPersonalizedRecommendationsResponse() {
    recommendations_ = java.util.Collections.emptyList();
    personalizationModel_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetPersonalizedRecommendationsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.recommendation.RecommendationReqResProto.internal_static_proto_recommendation_GetPersonalizedRecommendationsResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetFeatureContributions();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.recommendation.RecommendationReqResProto.internal_static_proto_recommendation_GetPersonalizedRecommendationsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse.class, com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse.Builder.class);
  }

  public static final int BASE_RESPONSE_FIELD_NUMBER = 1;
  private com.movieplatform.proto.common.BaseResponse baseResponse_;
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  @java.lang.Override
  public boolean hasBaseResponse() {
    return baseResponse_ != null;
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }

  public static final int RECOMMENDATIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.movieplatform.proto.recommendation.PersonalizedRecommendationItem> recommendations_;
  /**
   * <pre>
   * List of recommended items
   * </pre>
   *
   * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.movieplatform.proto.recommendation.PersonalizedRecommendationItem> getRecommendationsList() {
    return recommendations_;
  }
  /**
   * <pre>
   * List of recommended items
   * </pre>
   *
   * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.movieplatform.proto.recommendation.PersonalizedRecommendationItemOrBuilder> 
      getRecommendationsOrBuilderList() {
    return recommendations_;
  }
  /**
   * <pre>
   * List of recommended items
   * </pre>
   *
   * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
   */
  @java.lang.Override
  public int getRecommendationsCount() {
    return recommendations_.size();
  }
  /**
   * <pre>
   * List of recommended items
   * </pre>
   *
   * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.recommendation.PersonalizedRecommendationItem getRecommendations(int index) {
    return recommendations_.get(index);
  }
  /**
   * <pre>
   * List of recommended items
   * </pre>
   *
   * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.recommendation.PersonalizedRecommendationItemOrBuilder getRecommendationsOrBuilder(
      int index) {
    return recommendations_.get(index);
  }

  public static final int PERSONALIZATION_MODEL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object personalizationModel_ = "";
  /**
   * <pre>
   * Model used for personalization
   * </pre>
   *
   * <code>string personalization_model = 3;</code>
   * @return The personalizationModel.
   */
  @java.lang.Override
  public java.lang.String getPersonalizationModel() {
    java.lang.Object ref = personalizationModel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      personalizationModel_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Model used for personalization
   * </pre>
   *
   * <code>string personalization_model = 3;</code>
   * @return The bytes for personalizationModel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPersonalizationModelBytes() {
    java.lang.Object ref = personalizationModel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      personalizationModel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FEATURE_CONTRIBUTIONS_FIELD_NUMBER = 4;
  private static final class FeatureContributionsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Float> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Float>newDefaultInstance(
                com.movieplatform.proto.recommendation.RecommendationReqResProto.internal_static_proto_recommendation_GetPersonalizedRecommendationsResponse_FeatureContributionsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.FLOAT,
                0F);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Float> featureContributions_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Float>
  internalGetFeatureContributions() {
    if (featureContributions_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FeatureContributionsDefaultEntryHolder.defaultEntry);
    }
    return featureContributions_;
  }
  public int getFeatureContributionsCount() {
    return internalGetFeatureContributions().getMap().size();
  }
  /**
   * <pre>
   * How each feature contributed
   * </pre>
   *
   * <code>map&lt;string, float&gt; feature_contributions = 4;</code>
   */
  @java.lang.Override
  public boolean containsFeatureContributions(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetFeatureContributions().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFeatureContributionsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Float> getFeatureContributions() {
    return getFeatureContributionsMap();
  }
  /**
   * <pre>
   * How each feature contributed
   * </pre>
   *
   * <code>map&lt;string, float&gt; feature_contributions = 4;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Float> getFeatureContributionsMap() {
    return internalGetFeatureContributions().getMap();
  }
  /**
   * <pre>
   * How each feature contributed
   * </pre>
   *
   * <code>map&lt;string, float&gt; feature_contributions = 4;</code>
   */
  @java.lang.Override
  public float getFeatureContributionsOrDefault(
      java.lang.String key,
      float defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Float> map =
        internalGetFeatureContributions().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * How each feature contributed
   * </pre>
   *
   * <code>map&lt;string, float&gt; feature_contributions = 4;</code>
   */
  @java.lang.Override
  public float getFeatureContributionsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Float> map =
        internalGetFeatureContributions().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseResponse_ != null) {
      output.writeMessage(1, getBaseResponse());
    }
    for (int i = 0; i < recommendations_.size(); i++) {
      output.writeMessage(2, recommendations_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(personalizationModel_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, personalizationModel_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFeatureContributions(),
        FeatureContributionsDefaultEntryHolder.defaultEntry,
        4);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResponse());
    }
    for (int i = 0; i < recommendations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, recommendations_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(personalizationModel_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, personalizationModel_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Float> entry
         : internalGetFeatureContributions().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Float>
      featureContributions__ = FeatureContributionsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, featureContributions__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse other = (com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse) obj;

    if (hasBaseResponse() != other.hasBaseResponse()) return false;
    if (hasBaseResponse()) {
      if (!getBaseResponse()
          .equals(other.getBaseResponse())) return false;
    }
    if (!getRecommendationsList()
        .equals(other.getRecommendationsList())) return false;
    if (!getPersonalizationModel()
        .equals(other.getPersonalizationModel())) return false;
    if (!internalGetFeatureContributions().equals(
        other.internalGetFeatureContributions())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResponse()) {
      hash = (37 * hash) + BASE_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResponse().hashCode();
    }
    if (getRecommendationsCount() > 0) {
      hash = (37 * hash) + RECOMMENDATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getRecommendationsList().hashCode();
    }
    hash = (37 * hash) + PERSONALIZATION_MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getPersonalizationModel().hashCode();
    if (!internalGetFeatureContributions().getMap().isEmpty()) {
      hash = (37 * hash) + FEATURE_CONTRIBUTIONS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFeatureContributions().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Personalized recommendations response
   * </pre>
   *
   * Protobuf type {@code proto.recommendation.GetPersonalizedRecommendationsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.recommendation.GetPersonalizedRecommendationsResponse)
      com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.recommendation.RecommendationReqResProto.internal_static_proto_recommendation_GetPersonalizedRecommendationsResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetFeatureContributions();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableFeatureContributions();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.recommendation.RecommendationReqResProto.internal_static_proto_recommendation_GetPersonalizedRecommendationsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse.class, com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse.Builder.class);
    }

    // Construct using com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      if (recommendationsBuilder_ == null) {
        recommendations_ = java.util.Collections.emptyList();
      } else {
        recommendations_ = null;
        recommendationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      personalizationModel_ = "";
      internalGetMutableFeatureContributions().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.recommendation.RecommendationReqResProto.internal_static_proto_recommendation_GetPersonalizedRecommendationsResponse_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse getDefaultInstanceForType() {
      return com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse build() {
      com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse buildPartial() {
      com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse result = new com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse result) {
      if (recommendationsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          recommendations_ = java.util.Collections.unmodifiableList(recommendations_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.recommendations_ = recommendations_;
      } else {
        result.recommendations_ = recommendationsBuilder_.build();
      }
    }

    private void buildPartial0(com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseResponse_ = baseResponseBuilder_ == null
            ? baseResponse_
            : baseResponseBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.personalizationModel_ = personalizationModel_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.featureContributions_ = internalGetFeatureContributions();
        result.featureContributions_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse) {
        return mergeFrom((com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse other) {
      if (other == com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse.getDefaultInstance()) return this;
      if (other.hasBaseResponse()) {
        mergeBaseResponse(other.getBaseResponse());
      }
      if (recommendationsBuilder_ == null) {
        if (!other.recommendations_.isEmpty()) {
          if (recommendations_.isEmpty()) {
            recommendations_ = other.recommendations_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRecommendationsIsMutable();
            recommendations_.addAll(other.recommendations_);
          }
          onChanged();
        }
      } else {
        if (!other.recommendations_.isEmpty()) {
          if (recommendationsBuilder_.isEmpty()) {
            recommendationsBuilder_.dispose();
            recommendationsBuilder_ = null;
            recommendations_ = other.recommendations_;
            bitField0_ = (bitField0_ & ~0x00000002);
            recommendationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecommendationsFieldBuilder() : null;
          } else {
            recommendationsBuilder_.addAllMessages(other.recommendations_);
          }
        }
      }
      if (!other.getPersonalizationModel().isEmpty()) {
        personalizationModel_ = other.personalizationModel_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      internalGetMutableFeatureContributions().mergeFrom(
          other.internalGetFeatureContributions());
      bitField0_ |= 0x00000008;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBaseResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.movieplatform.proto.recommendation.PersonalizedRecommendationItem m =
                  input.readMessage(
                      com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.parser(),
                      extensionRegistry);
              if (recommendationsBuilder_ == null) {
                ensureRecommendationsIsMutable();
                recommendations_.add(m);
              } else {
                recommendationsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              personalizationModel_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Float>
              featureContributions__ = input.readMessage(
                  FeatureContributionsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableFeatureContributions().getMutableMap().put(
                  featureContributions__.getKey(), featureContributions__.getValue());
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.movieplatform.proto.common.BaseResponse baseResponse_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> baseResponseBuilder_;
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return Whether the baseResponse field is set.
     */
    public boolean hasBaseResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return The baseResponse.
     */
    public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
      if (baseResponseBuilder_ == null) {
        return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      } else {
        return baseResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResponse_ = value;
      } else {
        baseResponseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(
        com.movieplatform.proto.common.BaseResponse.Builder builderForValue) {
      if (baseResponseBuilder_ == null) {
        baseResponse_ = builderForValue.build();
      } else {
        baseResponseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder mergeBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseResponse_ != null &&
          baseResponse_ != com.movieplatform.proto.common.BaseResponse.getDefaultInstance()) {
          getBaseResponseBuilder().mergeFrom(value);
        } else {
          baseResponse_ = value;
        }
      } else {
        baseResponseBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder clearBaseResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponse.Builder getBaseResponseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBaseResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
      if (baseResponseBuilder_ != null) {
        return baseResponseBuilder_.getMessageOrBuilder();
      } else {
        return baseResponse_ == null ?
            com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> 
        getBaseResponseFieldBuilder() {
      if (baseResponseBuilder_ == null) {
        baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder>(
                getBaseResponse(),
                getParentForChildren(),
                isClean());
        baseResponse_ = null;
      }
      return baseResponseBuilder_;
    }

    private java.util.List<com.movieplatform.proto.recommendation.PersonalizedRecommendationItem> recommendations_ =
      java.util.Collections.emptyList();
    private void ensureRecommendationsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        recommendations_ = new java.util.ArrayList<com.movieplatform.proto.recommendation.PersonalizedRecommendationItem>(recommendations_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.movieplatform.proto.recommendation.PersonalizedRecommendationItem, com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.Builder, com.movieplatform.proto.recommendation.PersonalizedRecommendationItemOrBuilder> recommendationsBuilder_;

    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public java.util.List<com.movieplatform.proto.recommendation.PersonalizedRecommendationItem> getRecommendationsList() {
      if (recommendationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(recommendations_);
      } else {
        return recommendationsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public int getRecommendationsCount() {
      if (recommendationsBuilder_ == null) {
        return recommendations_.size();
      } else {
        return recommendationsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public com.movieplatform.proto.recommendation.PersonalizedRecommendationItem getRecommendations(int index) {
      if (recommendationsBuilder_ == null) {
        return recommendations_.get(index);
      } else {
        return recommendationsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public Builder setRecommendations(
        int index, com.movieplatform.proto.recommendation.PersonalizedRecommendationItem value) {
      if (recommendationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecommendationsIsMutable();
        recommendations_.set(index, value);
        onChanged();
      } else {
        recommendationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public Builder setRecommendations(
        int index, com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.Builder builderForValue) {
      if (recommendationsBuilder_ == null) {
        ensureRecommendationsIsMutable();
        recommendations_.set(index, builderForValue.build());
        onChanged();
      } else {
        recommendationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public Builder addRecommendations(com.movieplatform.proto.recommendation.PersonalizedRecommendationItem value) {
      if (recommendationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecommendationsIsMutable();
        recommendations_.add(value);
        onChanged();
      } else {
        recommendationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public Builder addRecommendations(
        int index, com.movieplatform.proto.recommendation.PersonalizedRecommendationItem value) {
      if (recommendationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecommendationsIsMutable();
        recommendations_.add(index, value);
        onChanged();
      } else {
        recommendationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public Builder addRecommendations(
        com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.Builder builderForValue) {
      if (recommendationsBuilder_ == null) {
        ensureRecommendationsIsMutable();
        recommendations_.add(builderForValue.build());
        onChanged();
      } else {
        recommendationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public Builder addRecommendations(
        int index, com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.Builder builderForValue) {
      if (recommendationsBuilder_ == null) {
        ensureRecommendationsIsMutable();
        recommendations_.add(index, builderForValue.build());
        onChanged();
      } else {
        recommendationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public Builder addAllRecommendations(
        java.lang.Iterable<? extends com.movieplatform.proto.recommendation.PersonalizedRecommendationItem> values) {
      if (recommendationsBuilder_ == null) {
        ensureRecommendationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recommendations_);
        onChanged();
      } else {
        recommendationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public Builder clearRecommendations() {
      if (recommendationsBuilder_ == null) {
        recommendations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        recommendationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public Builder removeRecommendations(int index) {
      if (recommendationsBuilder_ == null) {
        ensureRecommendationsIsMutable();
        recommendations_.remove(index);
        onChanged();
      } else {
        recommendationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.Builder getRecommendationsBuilder(
        int index) {
      return getRecommendationsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public com.movieplatform.proto.recommendation.PersonalizedRecommendationItemOrBuilder getRecommendationsOrBuilder(
        int index) {
      if (recommendationsBuilder_ == null) {
        return recommendations_.get(index);  } else {
        return recommendationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public java.util.List<? extends com.movieplatform.proto.recommendation.PersonalizedRecommendationItemOrBuilder> 
         getRecommendationsOrBuilderList() {
      if (recommendationsBuilder_ != null) {
        return recommendationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(recommendations_);
      }
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.Builder addRecommendationsBuilder() {
      return getRecommendationsFieldBuilder().addBuilder(
          com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.getDefaultInstance());
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.Builder addRecommendationsBuilder(
        int index) {
      return getRecommendationsFieldBuilder().addBuilder(
          index, com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.getDefaultInstance());
    }
    /**
     * <pre>
     * List of recommended items
     * </pre>
     *
     * <code>repeated .proto.recommendation.PersonalizedRecommendationItem recommendations = 2;</code>
     */
    public java.util.List<com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.Builder> 
         getRecommendationsBuilderList() {
      return getRecommendationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.movieplatform.proto.recommendation.PersonalizedRecommendationItem, com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.Builder, com.movieplatform.proto.recommendation.PersonalizedRecommendationItemOrBuilder> 
        getRecommendationsFieldBuilder() {
      if (recommendationsBuilder_ == null) {
        recommendationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.movieplatform.proto.recommendation.PersonalizedRecommendationItem, com.movieplatform.proto.recommendation.PersonalizedRecommendationItem.Builder, com.movieplatform.proto.recommendation.PersonalizedRecommendationItemOrBuilder>(
                recommendations_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        recommendations_ = null;
      }
      return recommendationsBuilder_;
    }

    private java.lang.Object personalizationModel_ = "";
    /**
     * <pre>
     * Model used for personalization
     * </pre>
     *
     * <code>string personalization_model = 3;</code>
     * @return The personalizationModel.
     */
    public java.lang.String getPersonalizationModel() {
      java.lang.Object ref = personalizationModel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personalizationModel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Model used for personalization
     * </pre>
     *
     * <code>string personalization_model = 3;</code>
     * @return The bytes for personalizationModel.
     */
    public com.google.protobuf.ByteString
        getPersonalizationModelBytes() {
      java.lang.Object ref = personalizationModel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personalizationModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Model used for personalization
     * </pre>
     *
     * <code>string personalization_model = 3;</code>
     * @param value The personalizationModel to set.
     * @return This builder for chaining.
     */
    public Builder setPersonalizationModel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      personalizationModel_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Model used for personalization
     * </pre>
     *
     * <code>string personalization_model = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPersonalizationModel() {
      personalizationModel_ = getDefaultInstance().getPersonalizationModel();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Model used for personalization
     * </pre>
     *
     * <code>string personalization_model = 3;</code>
     * @param value The bytes for personalizationModel to set.
     * @return This builder for chaining.
     */
    public Builder setPersonalizationModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      personalizationModel_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Float> featureContributions_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Float>
        internalGetFeatureContributions() {
      if (featureContributions_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FeatureContributionsDefaultEntryHolder.defaultEntry);
      }
      return featureContributions_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Float>
        internalGetMutableFeatureContributions() {
      if (featureContributions_ == null) {
        featureContributions_ = com.google.protobuf.MapField.newMapField(
            FeatureContributionsDefaultEntryHolder.defaultEntry);
      }
      if (!featureContributions_.isMutable()) {
        featureContributions_ = featureContributions_.copy();
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return featureContributions_;
    }
    public int getFeatureContributionsCount() {
      return internalGetFeatureContributions().getMap().size();
    }
    /**
     * <pre>
     * How each feature contributed
     * </pre>
     *
     * <code>map&lt;string, float&gt; feature_contributions = 4;</code>
     */
    @java.lang.Override
    public boolean containsFeatureContributions(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetFeatureContributions().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFeatureContributionsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Float> getFeatureContributions() {
      return getFeatureContributionsMap();
    }
    /**
     * <pre>
     * How each feature contributed
     * </pre>
     *
     * <code>map&lt;string, float&gt; feature_contributions = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Float> getFeatureContributionsMap() {
      return internalGetFeatureContributions().getMap();
    }
    /**
     * <pre>
     * How each feature contributed
     * </pre>
     *
     * <code>map&lt;string, float&gt; feature_contributions = 4;</code>
     */
    @java.lang.Override
    public float getFeatureContributionsOrDefault(
        java.lang.String key,
        float defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Float> map =
          internalGetFeatureContributions().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * How each feature contributed
     * </pre>
     *
     * <code>map&lt;string, float&gt; feature_contributions = 4;</code>
     */
    @java.lang.Override
    public float getFeatureContributionsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Float> map =
          internalGetFeatureContributions().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearFeatureContributions() {
      bitField0_ = (bitField0_ & ~0x00000008);
      internalGetMutableFeatureContributions().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * How each feature contributed
     * </pre>
     *
     * <code>map&lt;string, float&gt; feature_contributions = 4;</code>
     */
    public Builder removeFeatureContributions(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableFeatureContributions().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Float>
        getMutableFeatureContributions() {
      bitField0_ |= 0x00000008;
      return internalGetMutableFeatureContributions().getMutableMap();
    }
    /**
     * <pre>
     * How each feature contributed
     * </pre>
     *
     * <code>map&lt;string, float&gt; feature_contributions = 4;</code>
     */
    public Builder putFeatureContributions(
        java.lang.String key,
        float value) {
      if (key == null) { throw new NullPointerException("map key"); }
      
      internalGetMutableFeatureContributions().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <pre>
     * How each feature contributed
     * </pre>
     *
     * <code>map&lt;string, float&gt; feature_contributions = 4;</code>
     */
    public Builder putAllFeatureContributions(
        java.util.Map<java.lang.String, java.lang.Float> values) {
      internalGetMutableFeatureContributions().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000008;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.recommendation.GetPersonalizedRecommendationsResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.recommendation.GetPersonalizedRecommendationsResponse)
  private static final com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse();
  }

  public static com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPersonalizedRecommendationsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetPersonalizedRecommendationsResponse>() {
    @java.lang.Override
    public GetPersonalizedRecommendationsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetPersonalizedRecommendationsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPersonalizedRecommendationsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.recommendation.GetPersonalizedRecommendationsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

