// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation/recommendation_req_res.proto

package com.movieplatform.proto.recommendation;

public interface GetRecommendationAnalyticsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.recommendation.GetRecommendationAnalyticsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return Whether the baseRequest field is set.
   */
  boolean hasBaseRequest();
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return The baseRequest.
   */
  com.movieplatform.proto.common.BaseRequest getBaseRequest();
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   */
  com.movieplatform.proto.common.BaseRequestOrBuilder getBaseRequestOrBuilder();

  /**
   * <pre>
   * Start date for analytics
   * </pre>
   *
   * <code>.proto.common.DateTime start_date = 2;</code>
   * @return Whether the startDate field is set.
   */
  boolean hasStartDate();
  /**
   * <pre>
   * Start date for analytics
   * </pre>
   *
   * <code>.proto.common.DateTime start_date = 2;</code>
   * @return The startDate.
   */
  com.movieplatform.proto.common.DateTime getStartDate();
  /**
   * <pre>
   * Start date for analytics
   * </pre>
   *
   * <code>.proto.common.DateTime start_date = 2;</code>
   */
  com.movieplatform.proto.common.DateTimeOrBuilder getStartDateOrBuilder();

  /**
   * <pre>
   * End date for analytics
   * </pre>
   *
   * <code>.proto.common.DateTime end_date = 3;</code>
   * @return Whether the endDate field is set.
   */
  boolean hasEndDate();
  /**
   * <pre>
   * End date for analytics
   * </pre>
   *
   * <code>.proto.common.DateTime end_date = 3;</code>
   * @return The endDate.
   */
  com.movieplatform.proto.common.DateTime getEndDate();
  /**
   * <pre>
   * End date for analytics
   * </pre>
   *
   * <code>.proto.common.DateTime end_date = 3;</code>
   */
  com.movieplatform.proto.common.DateTimeOrBuilder getEndDateOrBuilder();

  /**
   * <pre>
   * Types of metrics to retrieve
   * </pre>
   *
   * <code>repeated string metric_types = 4;</code>
   * @return A list containing the metricTypes.
   */
  java.util.List<java.lang.String>
      getMetricTypesList();
  /**
   * <pre>
   * Types of metrics to retrieve
   * </pre>
   *
   * <code>repeated string metric_types = 4;</code>
   * @return The count of metricTypes.
   */
  int getMetricTypesCount();
  /**
   * <pre>
   * Types of metrics to retrieve
   * </pre>
   *
   * <code>repeated string metric_types = 4;</code>
   * @param index The index of the element to return.
   * @return The metricTypes at the given index.
   */
  java.lang.String getMetricTypes(int index);
  /**
   * <pre>
   * Types of metrics to retrieve
   * </pre>
   *
   * <code>repeated string metric_types = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the metricTypes at the given index.
   */
  com.google.protobuf.ByteString
      getMetricTypesBytes(int index);

  /**
   * <pre>
   * Aggregation level (hour/day/week/month)
   * </pre>
   *
   * <code>string aggregation_level = 5;</code>
   * @return The aggregationLevel.
   */
  java.lang.String getAggregationLevel();
  /**
   * <pre>
   * Aggregation level (hour/day/week/month)
   * </pre>
   *
   * <code>string aggregation_level = 5;</code>
   * @return The bytes for aggregationLevel.
   */
  com.google.protobuf.ByteString
      getAggregationLevelBytes();
}
