// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation/recommendation_req_res.proto

package com.movieplatform.proto.recommendation;

public interface UpdateRecommendationModelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.recommendation.UpdateRecommendationModelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  boolean hasBaseResponse();
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  com.movieplatform.proto.common.BaseResponse getBaseResponse();
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder();

  /**
   * <pre>
   * ID of the updated model
   * </pre>
   *
   * <code>string updated_model_id = 2;</code>
   * @return The updatedModelId.
   */
  java.lang.String getUpdatedModelId();
  /**
   * <pre>
   * ID of the updated model
   * </pre>
   *
   * <code>string updated_model_id = 2;</code>
   * @return The bytes for updatedModelId.
   */
  com.google.protobuf.ByteString
      getUpdatedModelIdBytes();

  /**
   * <pre>
   * New model version
   * </pre>
   *
   * <code>string new_version = 3;</code>
   * @return The newVersion.
   */
  java.lang.String getNewVersion();
  /**
   * <pre>
   * New model version
   * </pre>
   *
   * <code>string new_version = 3;</code>
   * @return The bytes for newVersion.
   */
  com.google.protobuf.ByteString
      getNewVersionBytes();

  /**
   * <pre>
   * Whether update was successful
   * </pre>
   *
   * <code>bool success = 4;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <pre>
   * When model was updated
   * </pre>
   *
   * <code>.proto.common.DateTime updated_at = 5;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <pre>
   * When model was updated
   * </pre>
   *
   * <code>.proto.common.DateTime updated_at = 5;</code>
   * @return The updatedAt.
   */
  com.movieplatform.proto.common.DateTime getUpdatedAt();
  /**
   * <pre>
   * When model was updated
   * </pre>
   *
   * <code>.proto.common.DateTime updated_at = 5;</code>
   */
  com.movieplatform.proto.common.DateTimeOrBuilder getUpdatedAtOrBuilder();
}
