# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from recommendation import recommendation_req_res_pb2 as recommendation_dot_recommendation__req__res__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recommendation/recommendation_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RecommendationServiceStub(object):
    """ML-based recommendation engine service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContentBasedRecommendations = channel.unary_unary(
                '/proto.recommendation.RecommendationService/GetContentBasedRecommendations',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.GetContentBasedRecommendationsRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.GetContentBasedRecommendationsResponse.FromString,
                _registered_method=True)
        self.GetSimilarContent = channel.unary_unary(
                '/proto.recommendation.RecommendationService/GetSimilarContent',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.GetSimilarContentRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.GetSimilarContentResponse.FromString,
                _registered_method=True)
        self.GetContentFeatures = channel.unary_unary(
                '/proto.recommendation.RecommendationService/GetContentFeatures',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.GetContentFeaturesRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.GetContentFeaturesResponse.FromString,
                _registered_method=True)
        self.GetCollaborativeRecommendations = channel.unary_unary(
                '/proto.recommendation.RecommendationService/GetCollaborativeRecommendations',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.GetCollaborativeRecommendationsRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.GetCollaborativeRecommendationsResponse.FromString,
                _registered_method=True)
        self.GetUserSimilarity = channel.unary_unary(
                '/proto.recommendation.RecommendationService/GetUserSimilarity',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.GetUserSimilarityRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.GetUserSimilarityResponse.FromString,
                _registered_method=True)
        self.GetItemSimilarity = channel.unary_unary(
                '/proto.recommendation.RecommendationService/GetItemSimilarity',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.GetItemSimilarityRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.GetItemSimilarityResponse.FromString,
                _registered_method=True)
        self.GetHybridRecommendations = channel.unary_unary(
                '/proto.recommendation.RecommendationService/GetHybridRecommendations',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.GetHybridRecommendationsRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.GetHybridRecommendationsResponse.FromString,
                _registered_method=True)
        self.GetPersonalizedRecommendations = channel.unary_unary(
                '/proto.recommendation.RecommendationService/GetPersonalizedRecommendations',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.GetPersonalizedRecommendationsRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.GetPersonalizedRecommendationsResponse.FromString,
                _registered_method=True)
        self.AnalyzeUserBehavior = channel.unary_unary(
                '/proto.recommendation.RecommendationService/AnalyzeUserBehavior',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.AnalyzeUserBehaviorRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.AnalyzeUserBehaviorResponse.FromString,
                _registered_method=True)
        self.TrackUserInteraction = channel.unary_unary(
                '/proto.recommendation.RecommendationService/TrackUserInteraction',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.TrackUserInteractionRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.TrackUserInteractionResponse.FromString,
                _registered_method=True)
        self.GetUserPreferences = channel.unary_unary(
                '/proto.recommendation.RecommendationService/GetUserPreferences',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.GetUserPreferencesRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.GetUserPreferencesResponse.FromString,
                _registered_method=True)
        self.TrainRecommendationModel = channel.unary_unary(
                '/proto.recommendation.RecommendationService/TrainRecommendationModel',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.TrainRecommendationModelRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.TrainRecommendationModelResponse.FromString,
                _registered_method=True)
        self.UpdateRecommendationModel = channel.unary_unary(
                '/proto.recommendation.RecommendationService/UpdateRecommendationModel',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.UpdateRecommendationModelRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.UpdateRecommendationModelResponse.FromString,
                _registered_method=True)
        self.GetModelPerformance = channel.unary_unary(
                '/proto.recommendation.RecommendationService/GetModelPerformance',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.GetModelPerformanceRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.GetModelPerformanceResponse.FromString,
                _registered_method=True)
        self.GetRecommendationAnalytics = channel.unary_unary(
                '/proto.recommendation.RecommendationService/GetRecommendationAnalytics',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.GetRecommendationAnalyticsRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.GetRecommendationAnalyticsResponse.FromString,
                _registered_method=True)
        self.GetRecommendationInsights = channel.unary_unary(
                '/proto.recommendation.RecommendationService/GetRecommendationInsights',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.GetRecommendationInsightsRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.GetRecommendationInsightsResponse.FromString,
                _registered_method=True)
        self.ExportRecommendationData = channel.unary_unary(
                '/proto.recommendation.RecommendationService/ExportRecommendationData',
                request_serializer=recommendation_dot_recommendation__req__res__pb2.ExportRecommendationDataRequest.SerializeToString,
                response_deserializer=recommendation_dot_recommendation__req__res__pb2.ExportRecommendationDataResponse.FromString,
                _registered_method=True)


class RecommendationServiceServicer(object):
    """ML-based recommendation engine service
    """

    def GetContentBasedRecommendations(self, request, context):
        """Content-based recommendations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimilarContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContentFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollaborativeRecommendations(self, request, context):
        """Collaborative filtering
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserSimilarity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemSimilarity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHybridRecommendations(self, request, context):
        """Hybrid recommendations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPersonalizedRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeUserBehavior(self, request, context):
        """Behavior analysis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackUserInteraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserPreferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainRecommendationModel(self, request, context):
        """Model management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRecommendationModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelPerformance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendationAnalytics(self, request, context):
        """Analytics and insights
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendationInsights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportRecommendationData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContentBasedRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContentBasedRecommendations,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.GetContentBasedRecommendationsRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.GetContentBasedRecommendationsResponse.SerializeToString,
            ),
            'GetSimilarContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimilarContent,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.GetSimilarContentRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.GetSimilarContentResponse.SerializeToString,
            ),
            'GetContentFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContentFeatures,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.GetContentFeaturesRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.GetContentFeaturesResponse.SerializeToString,
            ),
            'GetCollaborativeRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollaborativeRecommendations,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.GetCollaborativeRecommendationsRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.GetCollaborativeRecommendationsResponse.SerializeToString,
            ),
            'GetUserSimilarity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSimilarity,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.GetUserSimilarityRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.GetUserSimilarityResponse.SerializeToString,
            ),
            'GetItemSimilarity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemSimilarity,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.GetItemSimilarityRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.GetItemSimilarityResponse.SerializeToString,
            ),
            'GetHybridRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHybridRecommendations,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.GetHybridRecommendationsRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.GetHybridRecommendationsResponse.SerializeToString,
            ),
            'GetPersonalizedRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPersonalizedRecommendations,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.GetPersonalizedRecommendationsRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.GetPersonalizedRecommendationsResponse.SerializeToString,
            ),
            'AnalyzeUserBehavior': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeUserBehavior,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.AnalyzeUserBehaviorRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.AnalyzeUserBehaviorResponse.SerializeToString,
            ),
            'TrackUserInteraction': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackUserInteraction,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.TrackUserInteractionRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.TrackUserInteractionResponse.SerializeToString,
            ),
            'GetUserPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserPreferences,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.GetUserPreferencesRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.GetUserPreferencesResponse.SerializeToString,
            ),
            'TrainRecommendationModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainRecommendationModel,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.TrainRecommendationModelRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.TrainRecommendationModelResponse.SerializeToString,
            ),
            'UpdateRecommendationModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRecommendationModel,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.UpdateRecommendationModelRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.UpdateRecommendationModelResponse.SerializeToString,
            ),
            'GetModelPerformance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelPerformance,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.GetModelPerformanceRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.GetModelPerformanceResponse.SerializeToString,
            ),
            'GetRecommendationAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendationAnalytics,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.GetRecommendationAnalyticsRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.GetRecommendationAnalyticsResponse.SerializeToString,
            ),
            'GetRecommendationInsights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendationInsights,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.GetRecommendationInsightsRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.GetRecommendationInsightsResponse.SerializeToString,
            ),
            'ExportRecommendationData': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportRecommendationData,
                    request_deserializer=recommendation_dot_recommendation__req__res__pb2.ExportRecommendationDataRequest.FromString,
                    response_serializer=recommendation_dot_recommendation__req__res__pb2.ExportRecommendationDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.recommendation.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.recommendation.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """ML-based recommendation engine service
    """

    @staticmethod
    def GetContentBasedRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/GetContentBasedRecommendations',
            recommendation_dot_recommendation__req__res__pb2.GetContentBasedRecommendationsRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.GetContentBasedRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSimilarContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/GetSimilarContent',
            recommendation_dot_recommendation__req__res__pb2.GetSimilarContentRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.GetSimilarContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContentFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/GetContentFeatures',
            recommendation_dot_recommendation__req__res__pb2.GetContentFeaturesRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.GetContentFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollaborativeRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/GetCollaborativeRecommendations',
            recommendation_dot_recommendation__req__res__pb2.GetCollaborativeRecommendationsRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.GetCollaborativeRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserSimilarity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/GetUserSimilarity',
            recommendation_dot_recommendation__req__res__pb2.GetUserSimilarityRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.GetUserSimilarityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItemSimilarity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/GetItemSimilarity',
            recommendation_dot_recommendation__req__res__pb2.GetItemSimilarityRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.GetItemSimilarityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHybridRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/GetHybridRecommendations',
            recommendation_dot_recommendation__req__res__pb2.GetHybridRecommendationsRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.GetHybridRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPersonalizedRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/GetPersonalizedRecommendations',
            recommendation_dot_recommendation__req__res__pb2.GetPersonalizedRecommendationsRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.GetPersonalizedRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeUserBehavior(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/AnalyzeUserBehavior',
            recommendation_dot_recommendation__req__res__pb2.AnalyzeUserBehaviorRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.AnalyzeUserBehaviorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackUserInteraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/TrackUserInteraction',
            recommendation_dot_recommendation__req__res__pb2.TrackUserInteractionRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.TrackUserInteractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/GetUserPreferences',
            recommendation_dot_recommendation__req__res__pb2.GetUserPreferencesRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.GetUserPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainRecommendationModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/TrainRecommendationModel',
            recommendation_dot_recommendation__req__res__pb2.TrainRecommendationModelRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.TrainRecommendationModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRecommendationModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/UpdateRecommendationModel',
            recommendation_dot_recommendation__req__res__pb2.UpdateRecommendationModelRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.UpdateRecommendationModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelPerformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/GetModelPerformance',
            recommendation_dot_recommendation__req__res__pb2.GetModelPerformanceRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.GetModelPerformanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecommendationAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/GetRecommendationAnalytics',
            recommendation_dot_recommendation__req__res__pb2.GetRecommendationAnalyticsRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.GetRecommendationAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecommendationInsights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/GetRecommendationInsights',
            recommendation_dot_recommendation__req__res__pb2.GetRecommendationInsightsRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.GetRecommendationInsightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportRecommendationData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.recommendation.RecommendationService/ExportRecommendationData',
            recommendation_dot_recommendation__req__res__pb2.ExportRecommendationDataRequest.SerializeToString,
            recommendation_dot_recommendation__req__res__pb2.ExportRecommendationDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
